### ISSUE TITLE
[Test] Oomph Setup QA

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1023]
The following scenarios should be tested to validate the Oomph based setup:

- [ ] Install a new developer's workspace on OSX and verify that all projects are present in the workspace, there are no errors in the workspace, and the emulator starts without error
- [ ] Repeat above for Linux

**Comment by dwoodard1** [comment]
This may be user error on my part, but I am still having the below issues with a fresh Oomph setup:

- The emulator (org.eclipse.kura.emulator -> Kura_Emulator_OSX.launch) doesn't start. I can provide the errors, but there are many. Are others using a different approach to start the emulator?
- There are errors in the projects (org.eclipse.kura.protocol.can, org.eclipse.kura.windows.clock, etc). These are present because we are not including the projects in the Maven build. Not sure we can do anything about this, but it may raise questions when users see the red X on the projects. Maybe documenting this is enough.

**Comment by ctron** [comment]
So for the ".can" protocol you need to actually download dependencies which seem to be optional. As the project it optional and only included in the build if the specific profile is enabled (default is disabled).

Of course we can enable the profile in the initial build.

The launch configuration I am using with the Oomph installer is "Eclipse Kura Emulator". And IIRC this should work on both Linux and Mac OS X.

**Comment by pgufAtIBM** [comment]
tested the Oomph installer to setup a developers workspace on a Windows 7 machine (shown at https://www.youtube.com/watch?v=RwE3tLtejHM&feature=youtu.be). Last year in August I was able (after some problems) to setup the development environment on windows 7. Therefore I used now again this approach and faced now following problems:
**Problem 1** occurred when the installer wanted to download the source code of kura from git (error logs say that the authentication failed: java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: git@github.com:eclipse/kura.git: Auth fail). I manually cloned the code to the path (no authentication was used) and then let Oomph the steps afterwards. Had this problem already last year, and solved it by cloning the github repo manually
**Problem 2** Plugin org.eclipse.tycho:tycho-maven-plugin:0.26.0 cannot be resolved:
[INFO] Scanning for projects...
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-maven-plugin/0.26.0/tycho-maven-plugin-0.26.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.26.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:0.26.0 @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.kura:kura:3.0.0-SNAPSHOT (C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\kura\manifest_pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.26.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:0.26.0: Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:0.26.0 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
Had this problem already last year, and solved it last year. Tried to remember what I did last year and searched on the internet, but could not solve yet the problem.
**Problem 3**: compile errors in workspace -> target definition(kura\target-definition\kura-equinox_3.11.1.target) points to some directions that do no longer exist (f. ex. kura\target-definition\common\repository\plugins, kura\target-definition\equinox_3.8.1\repository\plugins). "Set target platform" like described here https://eclipse.github.io/kura/doc/kura-setup.html does not work.

Does somebody know how to solve the Tycho problem and the no longer valid paths in the target definition?
Thanks in advance

**Comment by dwoodard1** [comment]
@ctron That emulator does work better, but there are two issues. One, it appears the "org.eclipse.kura.example.beacon.scanner" is selected to run, this should be deselected. Two, the persistent directories (snapshots/ and data/) are created in the kura/distrib folder. I am not sure they belong there. Historically these were kept in the workspace directory.

I also think we should clean up the existing launch configurations. There are too many and likely confusing to new comers.

@pgufAtIBM It would be interesting to get your feedback on using Oomph on a Windows platform. We have only tested on OSX/Linux. I would start with a clean install as I think Problem 1 could be causing a lot of the errors. To get around the error, you need to set the "Eclipse Kura Git repository:" variable to "HTTPS (read/write)". The "Git (read/write)" option only works if you have entered your git credentials in the Eclipse IDE previously. 

![image](https://cloud.githubusercontent.com/assets/1392274/22265648/89ef4eee-e242-11e6-98b3-e415a69b069a.png)

**Comment by pgufAtIBM** [comment]
@dwoodard1: thank you for your comment. I changed in the Eclipse Installer, "Variables" view to "HTTP read / write", entered my mail address. Before clicking at the button "Finish" I added in Eclipse (Neon 2) following settings under "Window" -> "Preferences":
"General" -> "Network Connection" -> "SSH2": double check here if private ssh key is set (how this can be done is described here: https://help.github.com/enterprise/2.2/user/articles/generating-an-ssh-key/)
"Team" -> "Git" -> "Configuration": http.sslVerify=false; http.postBuffer=52428800
Then clicking at "Finish" in the Eclipse Installer, code was loaded successfully. 

At the step of launch setups some warnings happen:
Performing Launch setups/launchers/build-target-platform.launch
Execute Debug Command
Connecting Git team provider.
Updating indexes
[INFO] Scanning for projects... 

[WARNING]  
[WARNING] Some problems were encountered while building the effective model for org.eclipse.kura:org.usb4java:bundle:1.2.1-SNAPSHOT 

[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java:jar should not point at files within the project directory, ${basedir}/src/lib/usb4java-1.2.0.jar will be unresolvable by dependent projects @ line 42, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.linux-arm:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-linux-arm.jar will be unresolvable by dependent projects @ line 50, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.linux-x86_64:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-linux-x86_64.jar will be unresolvable by dependent projects @ line 58, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.linux-x86:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-linux-x86.jar will be unresolvable by dependent projects @ line 66, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.osx-x86:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-osx-x86.jar will be unresolvable by dependent projects @ line 74, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.osx-x86_64:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-osx-x86_64.jar will be unresolvable by dependent projects @ line 82, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.windows-x86_64:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-windows-x86_64.jar will be unresolvable by dependent projects @ line 91, column 25 
[WARNING] 'dependencies.dependency.systemPath' for org.usb4java:org.usb4java.windows-x86:jar should not point at files within the project directory, ${basedir}/src/lib/libusb4java-1.2.0-windows-x86.jar will be unresolvable by dependent projects @ line 99, column 25 
[WARNING]  
[WARNING] Some problems were encountered while building the effective model for org.eclipse.kura:usb4java-javax:bundle:1.2.1-SNAPSHOT 
[WARNING] 'dependencies.dependency.systemPath' for javax.usb:usb-api:jar should not point at files within the project directory, ${basedir}/src/lib/usb-api-1.0.2.jar will be unresolvable by dependent projects @ line 32, column 25 
[WARNING] 'dependencies.dependency.systemPath' for usb4java-javax:org.usb4java.javax:jar should not point at files within the project directory, ${basedir}/src/lib/usb4java-javax-1.2.0.jar will be unresolvable by dependent projects @ line 40, column 25 
[WARNING]  
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build. 
[WARNING]  
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects. 
[WARNING]  

These warnings are for usb part, which results then in build failure:
[INFO] ------------------------------------------------------------------------ 
[INFO] Reactor Summary: 
[INFO]  
[INFO] target-platform .................................... SUCCESS [  1.209 s] 
[INFO] Camel :: Core :: Import sun.misc ................... SUCCESS [  1.672 s] 
[INFO] System extension fragment for 'sun.misc' ........... SUCCESS [  0.222 s] 
[INFO] Java API for working with Human Interface USB Devices (HID) FAILURE [  0.618 s] 
[INFO] usb4java ........................................... SKIPPED 
[INFO] usb4java-javax ..................................... SKIPPED 
[INFO] Serial Device based on SODA DK comm ................ SKIPPED 
[INFO] jdk.dio-parent ..................................... SKIPPED 
[INFO] jdk.dio ............................................ SKIPPED 
[INFO] jdk.dio.armv5sf .................................... SKIPPED 
[INFO] jdk.dio.armv6hf .................................... SKIPPED 
[INFO] jdk.dio.x86 ........................................ SKIPPED 
[INFO] jdk.dio.x86_64 ..................................... SKIPPED 
[INFO] gwt-user ........................................... SKIPPED 
[INFO] moquette-broker .................................... SKIPPED 
[INFO] p2-repo-common ..................................... SKIPPED 
[INFO] p2-repo-equinox_3.11.1 ............................. SKIPPED 
[INFO] p2-repo-tests-deps ................................. SKIPPED 
[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD FAILURE 
[INFO] ------------------------------------------------------------------------ 
[INFO] Total time: 5.579 s 
[INFO] Finished at: 2017-01-25T15:43:10+01:00 

[INFO] Final Memory: 20M/104M 
[INFO] ------------------------------------------------------------------------ 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-validation) on project com.codeminders.hidapi: Failed during checkstyle execution: There are 7 errors reported by Checkstyle 6.11.2 with ../checkstyle_checks.xml ruleset. -> [Help 1] 
[ERROR]  
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. 
[ERROR] Re-run Maven using the -X switch to enable full debug logging. 
[ERROR]  
[ERROR] For more information about the errors and possible solutions, please read the following articles: 
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException 
[ERROR]  
[ERROR] After correcting the problems, you can resume the build with the command 
[ERROR]   mvn <goals> -rf :com.codeminders.hidapi 

Finally following error happens:
Updating Git status for repository kura:  12% ( 390/3014)
[WARNING] No explicit target runtime environment configuration. Build is platform dependent. 

[INFO] Computing target platform for MavenProject: org.eclipse.kura:org.eclipse.kura.api:1.2.0-SNAPSHOT @ C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\kura\org.eclipse.kura.api\pom.xml 

Searching for markers
Process resource updates
[INFO] Adding repository file://C:/IoT/EclipseKura/EclipseInstaller/iot-kura-develop-2017/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository 

[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location file:////C:/IoT/EclipseKura/EclipseInstaller/iot-kura-develop-2017/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository/: URI has an authority component -> [Help 1] 

	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121) 

	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) 
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) 
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) 

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
	at java.lang.reflect.Method.invoke(Unknown Source) 
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) 
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) 
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) 

	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) 

Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location file:////C:/IoT/EclipseKura/EclipseInstaller/iot-kura-develop-2017/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository/ 
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302) 

	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270) 
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176) 
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128) 
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1) 
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84) 
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223) 
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109) 
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95) 
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266) 
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) 
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) 

	... 11 more 
Caused by: org.eclipse.equinox.p2.core.ProvisionException: URI has an authority component 
	at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.<init>(ProfileMetadataRepository.java:50) 

	at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepositoryFactory.load(ProfileMetadataRepositoryFactory.java:36) 
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57) 
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768) 
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668) 
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96) 

	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61) 
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53) 
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298) 
	... 22 more 

Caused by: java.lang.IllegalArgumentException: URI has an authority component 
	at java.io.File.<init>(Unknown Source) 

	at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.getProfile(ProfileMetadataRepository.java:173) 
	at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.<init>(ProfileMetadataRepository.java:48) 
	... 30 more 
[ERROR]  

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. 
[ERROR] Re-run Maven using the -X switch to enable full debug logging. 
[ERROR]  
[ERROR] For more information about the errors and possible solutions, please read the following articles: 

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by pgufAtIBM** [comment]
executed _mvn compile_ in git\kura\target-platform path provided more details: seams that in some code files Windows line endings are used:
[INFO] ------------------------------------------------------------------------
[INFO] Building Java API for working with Human Interface USB Devices (HID) 1.1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle-validation) @ com.codeminders.hidapi ---
[INFO] Starting audit...
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\ClassPathLibraryLoader.java:1: error: Do not use Windows line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\HIDAPITest.java:1: error: Do not use Windows  line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\HIDDevice.java:1: error: Do not use Windows line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\HIDDeviceInfo.java:1: error: Do not use Windows line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\HIDDeviceNotFoundException.java:1: error: Do not use Windows line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapi\HIDManager.java:1: error: Do not use Windows  line endings
C:\IoT\EclipseKura\EclipseInstaller\iot-kura-develop-2017\git\kura\target-platform\com.codeminders.hidapi\src\main\java\com\codeminders\hidapplet\HidApplet.java:1: error: Do not use Windows line endings
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] target-platform ................................... SUCCESS [1.095s]
[INFO] Camel :: Core :: Import sun.misc .................. SUCCESS [0.571s]
[INFO] System extension fragment for 'sun.misc' .......... SUCCESS [0.046s]
[INFO] Java API for working with Human Interface USB Devices (HID)  FAILURE [0.376s]
[INFO] usb4java .......................................... SKIPPED
[INFO] usb4java-javax .................................... SKIPPED
[INFO] Serial Device based on SODA DK comm ............... SKIPPED
[INFO] jdk.dio-parent .................................... SKIPPED
[INFO] jdk.dio ........................................... SKIPPED
[INFO] jdk.dio.armv5sf ................................... SKIPPED
[INFO] jdk.dio.armv6hf ................................... SKIPPED
[INFO] jdk.dio.x86 ....................................... SKIPPED
[INFO] jdk.dio.x86_64 .................................... SKIPPED
[INFO] gwt-user .......................................... SKIPPED
[INFO] moquette-broker ................................... SKIPPED
[INFO] p2-repo-common .................................... SKIPPED
[INFO] p2-repo-equinox_3.11.1 ............................ SKIPPED
[INFO] p2-repo-tests-deps ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by pgufAtIBM** [comment]
looked into where the error for "Do not use Windows line endings" comes from: 
git\kura\checkstyle_checks.xml:

```
 <module name="RegexpMultiline">
      <property name="format" value="(?s:\r\n.*)"/>
      <property name="fileExtensions" value="java"/>
      <property name="message" value="Do not use Windows line endings"/>
  </module>
```

@LucaDazi: saw that the listed files were commited by you. can you please have a look? Thanks

**Comment by cdealti** [comment]
@ctron @dwoodard1 this is not currently assigned. 

@markoer is the Eclipse installer (Oomph) covered by the QA validation spreadsheet? On what operating systems?

**Comment by markoer** [comment]
A new test case has been added: UW-OOMPH-001.
I ran it only on Linux/Ubuntu.
It does not yet include a step where emulator would be run.

**Comment by dwoodard1** [comment]
@ctron The initial setup with Oomph is great, but I ran into issues when updating/building. Does this setup expect the user to use the Eclipse Git and Maven integrated tools? I use 100% command line for managing Git and performing Maven builds. This seemed to confuse the Eclipse IDE setup with the Oomph installer. I can provide more details, but I was curious on your typical workflow. Do you build Kura and manage Git within the Eclipse IDE?

**Comment by ctron** [comment]
I don't have much issues there. I do run most tasks from the Eclipse IDE though. Sometimes I do use Maven from the command line, which works fine. Git from the command line is a thing I do quite rarely. But even then, it works.

**Comment by dwoodard1** [comment]
Ok, good to know. Primarily I was having an issue with the web bundle class files not getting updated after a Maven compile. I will try and get more concrete errors and logs and report back.

**Comment by ctron** [comment]
Well the web bundle has to be re-compiled manually after every change. That is just GWT ...

**Comment by dwoodard1** [comment]
Re-compiled manually? With my "traditional" setup (import as Maven project), all I have to do is perform the Maven build (which performs the GWT compile), and then my new classes are updated in Eclipse so I can run the emulator. Are you saying you perform a GWT compile in Eclipse outside of the Maven build? I will find what is wrong with my Oomp setup and report back.

**Comment by ctron** [comment]
Yea, that is what I meant. I do either `mvn package` from the command line or "Run as -> Maven install" from the IDE. Or using the Maven launcher "build-web-ui-2".

I can then run from inside the IDE afterwards as well.

I have to do this every time I change something in the "web2" project or when I switch branches and changes got made in this project.

**Comment by marentwickler** [comment]
I find great difficulties with kura installation,I use eclipse Installer  .I can't to build kura project by installing, the issue is :' Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location    ......     No repository found at  file://..../ iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository. -> [Help 1]'. 
![screen shot 2017-04-24 at 00 07 11](https://cloud.githubusercontent.com/assets/11528983/25318207/0435cebe-2882-11e7-97bd-fcfaaf1531a6.png).
Thanks in advance

**Comment by mvtn** [comment]
Hello,

I'm installing eclipse Kura with eclipse committers on windows 10 machine, I use eclipse installer and it is giving me below error:

![image](https://cloud.githubusercontent.com/assets/28703294/26209451/3b56a144-3bc3-11e7-943f-4d6b7f8ae170.png)

Thanks in advance.

**Comment by MMaiero** [comment]
@markoer Can you please do a full test if this feature works?
With the latest changes you made, does this work now for Windows systems?
Thanks

**Comment by markoer** [comment]
With #1495 the oomph setup produces more complete working sets and emulator runs with H2 DB support.
With #1496 build runs on Windows. But emulator still won't run properly with the same issue as before - port 8080 is open with server listening, but faces some kind of proxy issues.

**Comment by mvtn** [comment]
Recently, I've installed eclipse Kura with eclipse installer on Linux/Centos machine. I set the  "Developer Type" to "User" and the "Eclipse Kura Git repository" to HTTPS (read/write). Now, I have the following projects in my workspace [1]:

- Other Projects [kura develop]
- Eclipse Kura [kura develop]
- Target Platform[kura develop]
- Examples

The org.eclipse.kura.api shows me the following error in pom.xml:
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:properties-maven-plugin:1.0-alpha-1:read-project-properties (execution: read-previous-release-versions, phase: initialize)    pom.xml    
Path: /org.eclipse.kura.api
Line: line 47 and 35. 
Type: Maven Project Build Lifecycle Mapping Problem

When I try to run the Kura_Emulator_Linux the Web UI does not show up in the browser. It gives me HTTP ERROR: 404 Error.       

In console of eclipse, I got some errors too, as follows: 
- log4j:ERROR Could not read configuration file from URL ...
- log4j:ERROR Ignoring configuration file [file:/home/k8s/iot-kura-develop/ws/kura/emulator/org.eclipse.kura.emulator/src/main/resources/log4j.properties].
- log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
- log4j:WARN Please initialize the log4j system properly.
- log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

I inputted 'ss' and its outputs are:                 
id	State       Bundle
0	ACTIVE      org.eclipse.osgi_3.11.1.v20160708-1632
	            Fragments=12
1	ACTIVE      org.eclipse.equinox.ds_1.4.400.v20160226-2036
2	ACTIVE      org.eclipse.equinox.metatype_1.4.200.v20160324-1850
3	ACTIVE      log4j_1.2.17
	            Fragments=51
4	ACTIVE      org.apache.commons.net_3.1.0.v201205071737
5	ACTIVE      org.eclipse.equinox.http.jetty_3.3.0.v20160324-1850
6	ACTIVE      com.google.protobuf_2.6.0
7	ACTIVE      org.apache.commons.lang3_3.4.0
8	ACTIVE      org.eclipse.kura.api_1.3.0.qualifier
9	ACTIVE      org.eclipse.jetty.servlet_9.3.9.v20160517
10	ACTIVE      org.apache.felix.gogo.shell_0.10.0.v201212101605
11	ACTIVE      org.apache.felix.dependencymanager_3.0.0
12	RESOLVED    org.eclipse.kura.sun.misc_1.0.0
	            Master=0
13	ACTIVE      usb4java-javax_1.2.200.SNAPSHOT
14	ACTIVE      org.eclipse.jetty.util_9.3.9.v20160517
15	ACTIVE      org.apache.commons.fileupload_1.3.2
16	ACTIVE      org.eclipse.equinox.common_3.8.0.v20160509-1230
17	ACTIVE      org.eclipse.kura.emulator_1.0.100.qualifier
18	ACTIVE      org.eclipse.equinox.io_1.1.100.v20150430-1834
19	ACTIVE      org.apache.felix.deploymentadmin_0.9.5
20	ACTIVE      org.apache.camel.camel-kura_2.17.2
21	ACTIVE      org.eclipse.equinox.console_1.1.200.v20150929-1405
22	ACTIVE      org.eclipse.jetty.continuation_9.3.9.v20160517
23	ACTIVE      org.apache.camel.camel-core-osgi_2.17.2
24	ACTIVE      org.eclipse.osgi.util_3.3.100.v20150423-1351
25	ACTIVE      org.eclipse.jetty.server_9.3.9.v20160517
26	ACTIVE      org.apache.commons.exec_1.3.0
27	ACTIVE      osgi.cmpn_4.3.0.201111022214
28	ACTIVE      slf4j.api_1.7.21
	            Fragments=34
29	ACTIVE      org.eclipse.equinox.wireadmin_1.0.600.v20150715-1528
30	ACTIVE      org.eclipse.equinox.util_1.0.500.v20130404-1337
31	ACTIVE      org.eclipse.jetty.http_9.3.9.v20160517
32	ACTIVE      org.eclipse.kura.demo.heater_1.0.200.qualifier
33	RESOLVED    org.eclipse.kura.camel.sun.misc_1.0.0
	            Master=47
34	RESOLVED    slf4j.log4j12_1.7.21
	            Master=28
35	ACTIVE      jcl.over.slf4j_1.7.21
36	ACTIVE      org.eclipse.equinox.event_1.3.200.v20160324-1850
37	ACTIVE      com.gwt.user_1.0.100
38	ACTIVE      org.eclipse.equinox.cm_1.1.200.v20160324-1850
39	ACTIVE      org.hsqldb.hsqldb_2.3.0
40	ACTIVE      org.eclipse.osgi.services_3.5.100.v20160504-1419
41	ACTIVE      org.apache.camel.camel-stream_2.17.2
42	ACTIVE      org.eclipse.jetty.security_9.3.9.v20160517
43	ACTIVE      org.usb4java_1.2.100
44	ACTIVE      org.eclipse.jetty.io_9.3.9.v20160517
45	ACTIVE      org.eclipse.equinox.http.servlet_1.3.1.v20160808-1329
46	ACTIVE      javax.servlet_3.1.0.v201410161800
47	ACTIVE      org.apache.camel.camel-core_2.17.2
	            Fragments=33
48	ACTIVE      org.eclipse.soda.dk.comm_1.2.100
49	ACTIVE      minimal-json_0.9.4
50	ACTIVE      org.apache.felix.gogo.command_0.10.0.v201209301215
51	RESOLVED    log4j.apache-log4j-extras_1.1.0
	            Master=3
52	ACTIVE      org.knowhowlab.osgi.monitoradmin_1.0.2
53	ACTIVE      org.apache.commons.io_2.4.0
54	ACTIVE      org.apache.felix.gogo.runtime_0.10.0.v201209301036
55	ACTIVE      usb4java-javax_1.2.100

Could someone help me to figure out what is going on?

Thanks in advance.

**Comment by markoer** [comment]
@mvtn I'm not entirely sure User type was meant to run the GUI part of Kura. What this setup allows you is to build your own bundle and deploy it to a running Kura instance.

You may safely ignore the api/pom.xml problem.

As for the log4j errors, you can try replacing all ${workspace_loc} with ${git_work_tree} in the Run Configurations->OSGi Framework->Kura_Emulator_Linux->VM arguments. That should get rid of those.

**Comment by mvtn** [comment]
@markoer I replaced all ${workspace_loc} with ${git_work_tree} and now i get no errors anymore. :)

Then, to run the GUI I must install the Eclipse Kura using the User Workspace? I downloaded the Kura User Workspace archive (user_workspace_archive_3.0.0.zip) and I have some projects in my workspace, as follows:
- org.eclipse.kura.demo.heater
- org.eclipse.kura.emulator
- org.eclipse.kura.example.beacon
- org.eclipse.kura.example.ble.tisensortag
- org.eclipse.kura.example.camel.aggregation
- org.eclipse.kura.example.camel.publisher
- org.eclipse.kura.example.camel.quickstart
- org.eclipse.kura.example.publisher
- target-definition

At this moment, I can use the Kura user workspace in local emulation mode :). However, I realized that I didn't have the org.eclipse.kura.api, I didn't have the Network option or the firewall in the System area on the Kura Gateway Administration Console either [1]. Is it ok? 

[1] [eclipse_kura_user_workspace](https://user-images.githubusercontent.com/28703294/28157062-a5fd54a4-678b-11e7-88c8-2eecc969513e.jpg)

Thank you for your detailed and informative reply.

**Comment by markoer** [comment]
By running Kura instance I meant the full Kura installed on a gateway, e.g. Raspberry Pi.

If you really want to run the emulator with a GUI using OOMPH setup, you could still use the Developer type for now. I have it on good authority that with some further development (already in progress) also User type will be able to do that.
Kura user workspace is definitely a good alternative. The org.eclipse.kura.api bundle is included as a binary in the equinox repository. You can include it in your projects as a dependency by adding its packages to the MANIFEST.MF file (see the heater demo or one of the example projects).

As far as the Network and Firewall services go, it is probably only wise not to attempt changing these settings on a user machine. So I would say that's the reason for them to be omitted.

**Comment by pierantoniomerlino** [comment]
@cdealti please review #1496
@markoer please write a summary of what works on Windows and how. Then we need to create a new documentation issue.

**Comment by markoer** [comment]
To summarize what works on Windows (after #1496):
* OOMPH
  * Eclipse and plugins install and setup
  * GIT repository cloning
  * project import
  * creation of working sets
  * build of target-platform/pom.xml
  * initial build of kura/pom.xml with skipped tests
* build of kura/test/pom.xml
* build of kura/examples/pom.xml
* build of karaf/pom.xml

Build of kura/distrib/pom.xml doesn't work and neither is it expected to work.

Web UI does not come up in the emulator on Windows.

**Comment by cdealti** [comment]
@MMaiero we should also add to the above list that the Web UI does not come up in the emulator. Correct?

**Comment by MMaiero** [comment]
Yes. I'll change the README file and I'll post a PR for that.
