### ISSUE TITLE
Ignore welcome message for Camel SCR XML routes

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#114]
We should support certain welcome message for Camel SCR XML routes. For example `"...Insert XML Camel route..."`. This message should be displayed in the Kura web UI, but should not be parsed by Camel module.

**Comment by cdealti** [comment]
We do not support this because there is no support in the metatype schema.

You can define your welcome message as the ``default`` value in the ``<AD/>`` element of the metatype (see [1]) and this will be displayed in the Web UI.

Note however that your ``ConfigurableComponent`` will receive this default value in the configuration properties Map (e.g. in the ``activate`` method). Your component will have to filter the welcome message.

We generally do not care about these welcome messages.

[1] https://github.com/eclipse/kura/blob/develop/kura/examples/org.eclipse.kura.example.publisher/OSGI-INF/metatype/org.eclipse.kura.example.publisher.ExamplePublisher.xml

**Comment by hekonsek** [comment]
I think we could add extra condition to `CamelRouter` which will ignore XML route definitions not containing `<route ` element. Such validation should solve the issue, as "welcome messages" usually doesn't contain `<route` elements.

This way `CamelRouter` will parse only real routes and ignore non-route default values.

**Comment by hekonsek** [comment]
Done.
