### ISSUE TITLE
Incorrectly configuring a component can be irreversable.

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#1161]
Kura 1.4

Via java/ConfigurationServiceImpl I've accidentally set 

org.eclipse.kura.watchdog.WatchdogService pingInterval="30000"

ie as a string.

This has invalidated the component.

 As a result, the configuration page no longer appears in the webconsole, and any further updates via java are ignored:

INFO  o.e.k.c.c.ConfigurationServiceImpl - UpdatingConfiguration ignored as ConfigurableComponent org.eclipse.kura.watchdog.WatchdogService is NOT tracked.

The only way to fix is to delete snapshots and restart.

**Comment by MMaiero** [comment]
I think that the real problem is at the component level.
As you can see here: https://github.com/eclipse/kura/blob/KURA_1.4.0_RELEASE/kura/org.eclipse.kura.linux.watchdog/src/main/java/org/eclipse/kura/linux/watchdog/WatchdogServiceImpl.java#L64
While starting, the component tries to cast the property as an Integer. This will fail and cause the component to not start.

**Comment by pstanton** [comment]
The failed cast is understandable, however the ability to change the value must be protected from failure.

**Comment by pstanton** [comment]
Just in case it wasn't clear in my previous reply - the real issue here is the unrecoverable state the environment falls into. if the cast fails, that can be logged/thrown, but the entire change to the state should be rolled back and allow the component to continue functioning in its last good state.
