### ISSUE TITLE
Add CamelKuraClient to Camel module 

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#117]
We need to migrate those [1] two [2] modules from Rhiot to Kura.

[1] https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/camel_components/kura_cloud.html
[2] https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/camel_components/camel_kura_cloud_service_bridge.html

**Comment by cdealti** [comment]
@kartben do you see any IP issues in migrating the source code mentioned above in the Kura github repository? Does it need a CQ?
Henryk is the original author of the work being migrated.

**Comment by cdealti** [comment]
@hekonsek Nice contribution!
I guess all this needs now to be integrated in the Kura ``CloudService`` to provide an alternate path for messages (``KuraPayloadS``) published and received through a ``CloudClient`` instance.

The ``CloudClient`` implementation, either the current one (let's call it the native CloudClient) or the ``CamelCloudClient`` decides where the message will be "routed".

With the native CloudClient the message is passed from the ``CloudService`` down to the ``DataService`` and sent via MQTT though the ``DataTransport``.

With the ``CamelCloudClient`` the message is effectively passed to Camel and routed accordingly to the Camel routes into effect.

The actual ``CloudClient`` is almost transparent to applications. Some operations are not meaningful for a CamelCloudClient and will throw an exception. However these operations are rarely used and we will not break most applications.

Is this a good enough explanation?

The piece missing is now modifying the ``CloudService`` in a way that its factory method ``newCloudClient()`` method will return by default a native CloudClient or CamelCloudClient accordingly to a CloudService configuration property.

Also, there might be explicit ``newNativeCloudClient()`` and ``newCamelCloudClient()``.
 
A few notes.
* @kartben Is the Apache (only) license header OK in f876d8ead9b600f5d1b7fa2a7ce0335a05f1e3a2?
* Can you avoid throwing unchecked Exceptions (like RuntimeException or UnsupportedOperationException) from methods already throwing a KuraException?
* Can you please use the Kura logger instead of the Camel logger and call it ``s_logger``?

**Comment by kartben** [comment]
The license needs to be EPL. 
Normally, the code would need to go through a CQ as it was not developped under the supervision of the Eclipse IoT PMC, and Henryk was not a committer at the time the code was written.
That being said, it looks like when the headers will have been switched to EPL license, it will likely be less than 1000 lines of code, so CQ is not needed :)

**Comment by hekonsek** [comment]
Mea culpa. I will change headers to EPL :) .

**Comment by cdealti** [comment]
Nooooo. Another CQ, please no :(.

**Comment by cdealti** [comment]
Before moving on, do you have comments on my above commit?

**Comment by hekonsek** [comment]
BTW I have fixed the license headers to match Eclipse license.

**Comment by hekonsek** [comment]
I really like your change [1] Cristiano. Good stuff!

[1] https://github.com/eclipse/kura/commit/9ca6be0b6376f748da72036387106ae4c3482c0c

**Comment by hekonsek** [comment]
I have created #127 to remember about KuraException refactoring. Thanks, Cristiano!

**Comment by hekonsek** [comment]
@cdealti What do you mean by "Kura logger"? :)

**Comment by cdealti** [comment]
In Kura we usually create a per-class slf4j Logger e.g.:
```
private static final Logger s_logger = LoggerFactory.getLogger(ExampleComponent.class);
```

**Comment by hekonsek** [comment]
I have fixed the logger convention - https://github.com/eclipse/kura/commit/41f5fe68fa9f06854c2ef2d6c29b5143e88c99fd .

**Comment by hekonsek** [comment]
I propose to close that task. We can work on the additional features in separated tasks to make our life easier.
