### ISSUE TITLE
[Camel] Migrate CamelRouter documentation from Rhiot to Kura

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#120]
We should migrate this [1] page from Rhiot documentation to Kura Wiki.

[1] https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/camel_kura_router.html

**Comment by hekonsek** [comment]
Add documentation here - https://github.com/eclipse/kura/tree/gh-pages/_posts/doc .

**Comment by hekonsek** [comment]
Done.

**Comment by pierantoniomerlino** [comment]
Hi,
I take a look on the documentation site and it seems that the Camel page has a different layout.
Could you please fix it? I think that in the document the header is missing (see the other posts in the _posts/doc directory). Moreover, could you move the images in the asset folder?

Finally, since the documentation server orders the post chronologically, could you adjust the date to move the post at the end on the list?

Thank you!

**Comment by pierantoniomerlino** [comment]
Hi,
I reopen the issue to track the modifications.

**Comment by pierantoniomerlino** [comment]
👍
