### ISSUE TITLE
[Wires] Implement regex filter WireComponent

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1211]
This WireComponent filter is used to filter out properties not matching a configurable regular expression.

**Comment by amitjoy** [comment]
Instead of creating a Wire Component to filter out keys from the associated map of Wire Records, we can also use the filter defined in Wire Configuration. This way we can apply filters on wire connections. Users can click on the wire connection in Wire Graph either to delete it or to associate a regex filter to it. The implementation for such a filter at the wire level needs very minimal changes in internal classes (no API breaking changes). I have also created a branch with the needed changes for such filter at the wire level. We can also discuss about it further.

**Comment by cdealti** [comment]
@amitjoy we need this for Kura 3.0. Can you share your preliminary work and list pros-and-cons of both approaches?
