### ISSUE TITLE
[Driver] DriverRecord and AssetRecord. Clean code vs efficiency

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1220]
From an API perspective, the independence between ``asset`` and ``driver`` packages is nice.
They can be used independently.

However in practice Asset implementations like BaseAsset have an associated Driver.

Since at the API level drivers and assets are independent they have their own records: AssetRecord and DriverRecord. This means that BaseAsset has to work a lot instantiating and copying lists of AssetRecords and DriverRecords for every read.

If an asset is configured with hundreds of channels to read there will be a significant overhead in terms of CPU and heap usage.

These useless allocations will be reduced by #1206 but they cannot be completely eliminated.

For efficiency it would be better to remove AssetRecord and use DriverRecord at the Asset layer too.
Maybe not as elegant as now...

**Comment by cdealti** [comment]
@amitjoy I beleive this needs to be addressed before Kura 3.0. What do you think?

**Comment by cdealti** [comment]
@nicolatimeus can you please measure the performance before we decide this needs to be optimized?

**Comment by amitjoy** [comment]
From the design point of view, `Asset` and `Driver` looks similar and the source base reflects the same. In addition, a `Driver` can also work in isolation, that is, the user is not obliged to use `Asset` always. Hence, a `Driver` can be used in other future scenarios as well due to clear separation.

On the other hand, `Asset` is a higher level abstraction to work on field devices and it uses a `Driver` instance to do so. From clean code perspective, the design as of now is clearly separated and both `Asset` and `Driver` designs are look-alike. It is easy to understand and easy to use. From performance point of view, there resides a slight performance hit as for every `DriverRecord` there will be an `AssetRecord`.

If we remove `AssetRecord` and provide a common data container class, we clearly are exposing lower level API to the higher level that I believe, is not a good design approach. As we are using powerful JDK 1.8, this performance hit would be minimal.

Let @nicolatimeus have some performance measurements concerning this.

**Comment by nicolatimeus** [comment]
I've performed a quick benchmark on a Raspberry PI 3 running Oracle JVM (build 1.8.0_65-b17), using the following wire graph:

**Timer** -> **DummyAsset** -> **Sink**

where:

*   **Timer** is a Timer component configured to tick every 20ms.

*   **DummyAsset** is an Asset attached to a driver instance that simply fills the provided DriverRecords with a constant value of the proper Java type.
  All defined channels are in READ mode and use Integer as value type.


* **Sink** is a WireReceiver that can be configured to operate in one of the following two modes:
    * *no-op*: The component does nothing inside its onWireReceive() method.
    * *print-statistics*: The component prints on the log the time interval measured between two successive wire envelopes.

The following software configurations has been tested:

* **develop**: Build of the develop branch at commit 7ad28975684c651551cc052951022d815d6e95f7 (sub-second timer).

* **fixed-asset-allocs**: Build of **develop** with PR #1266.

* **no-service-references**: Build of **develop** with PRs #1266 and #1272.

* **asset-refactor**: A quick attempt to merge AssetRecord and DriverRecord in a new class, ChannelRecord, which is shared between Asset and Driver.
This build also includes the improvements submitted in PRs #1266 and #1272.

#### Channel count vs CPU load

This table reports the average CPU used by the java process measured using the top utility vs the number of channels defined on the asset.
During the benchmark the **Sink** component was configured in no-op mode and no Web UI windows were open.

| Channel count  | develop | fixed-asset-allocs | no-service-references | asset-refactor |
| - | - | - | - | - |
| 10 | 30%| 15%| 6% | 6%|
| 20 | 60%| 17%| 7% | 6%|
| 50 | 100%| 20%| 10% | 7%|
| 100 | 100%| 25%| 15% | 10%|
| 200 | 100%| 35%| 25% | 15%|

#### Mean time between two successive garbage collections

| Channel count  | develop | fixed-asset-allocs | no-service-references | asset-refactor |
| - | - | - | - | - |
| 200 | 900ms | 13s | 13s | 22s |

####  Channel count vs time between two envelopes

During this benchmark the **Sink** component was configured in print-statistics mode, the average time between two successive received envelopes is reported in the table below.

| Channel count  | develop |
| - | - |
| 10 | 20ms |
| 20 | 20ms |
| 50 | ~50ms |
| 100 | ~170ms |
| 200 | ~700ms |

For the other configurations the measured timings were around 20ms.

**Comment by MMaiero** [comment]
Maybe we could name `ChannelRecord` as `DataRecord`, or something like that, in order to try to abstract the concept of Channel that is proper only for the Asset

**Comment by MMaiero** [comment]
Anyway, the difference is really impressive and, in my opinion, we should definitely move for this set of refactorings.
