### ISSUE TITLE
Commit aa2913dc1031e783d09779dae503018da55889f6 breaks asset persistent storage

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1222]
Commit aa2913dc1031e783d09779dae503018da55889f6 meant for "Added functionality to allow adding Wire Components after removing one" effectively breaks the wires: assets configuration is indeed not persistently stored. 
A reboot will determine an internal error and the framework will become unusable via web UI.

@amitjoy Could you please have a look and try to find a solution?

**Comment by MMaiero** [comment]
That commit was carried by PR #1126

**Comment by amitjoy** [comment]
You are right. Only Asset configurations are not getting persisted. So far I have not found any potential issue in Wires Source base that could have triggered such issue. While saving the Wire Graph, we invoke `configService.updateConfiguration(WIRE_SERVICE_PID, props, true)` which is supposed to build the current configuration and save it in snapshot (due to `true` as the boolean argument) . In `ConfigurationServiceimpl`, the `updateConfigurationsInternal` method is invoked to build list of `ComponentConfiguration`s that are present in runtime. Even though the Asset configuration is already present in the runtime, the list of `ComponentConfiguration`s does not contain the Asset configuration. That is quite weird.

**Comment by MMaiero** [comment]
Maybe it is a matter of timing?
Maybe when you invoke the creation of snapshot the asset is still not alive and tracked.

**Comment by amitjoy** [comment]
Yeah you are right. `createFactoryConfigurtion` method does not return boolean to indicate whether the factory has already been created or not. It could be a timing issue.
