### ISSUE TITLE
PR #1126 breaks changes to wire graph that were not saved

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1277]
Commit aa2913dc1031e783d09779dae503018da55889f6 in PR #1126 basically breaks the storage of changes that were performed before saving of the wire graph.
In brief, if you drop a component to the graph, perform some changes to the component configuration, than click outside the component. When you re-click again to the component, the changes done before will be lost.

@amitjoy Could you give it a look, please?

**Comment by amitjoy** [comment]
As far as I checked quickly that this functionality was not present since beginning. On clicking on any Wire Component in the Wire Graph simply invokes a properties retrieval function. In case the Wire Component is not available in the OSGi runtime, it shows the default properties. If you drop a Wire Component to the Wire Graph, on clicking on it, every time only the associated properties are retrieved.

This will require a new functionality to be implemented to not discard any local changes.
