### ISSUE TITLE
[Discussion] Add Felix Install to Kura

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#133]
Hi,

I'd like to add Felix Install [1] to Kura. And configure it to automatically pick up and install bundles dropped into `/opt/eclipse/kura/kura/deploy` directory. This way we could achieve Karaf-like deployment experience.

What do you think guys? Any objections?

Cheers! 

[1] http://felix.apache.org/documentation/subprojects/apache-felix-file-install.html

**Comment by dwoodard1** [comment]
@hekonsek @ctron Is this the same request as #99? I would love to have Kura Karaf ready, but would like input on the best way to implement this. Is the Smarthome feature approach the best model?

**Comment by ctron** [comment]
No. This is something different. This one is about adding "Felix file install", which allows dropping in bundles into a directory, which get's then picked up by OSGi. A Karaf feature is something different.

As discussed in the F2F meeting I am already working on a proof-of-concept for Karaf. Right now the biggest issued are the System.exit() issue and the way the SystemService is used. I am already in the process of providing some PRs for fixing this. I will issue a few PRs in the next weeks which make those changes so that we can review them.

**Comment by ccustine** [comment]
I was looking for a way to install bundles/dps from command line and found this issue. I also 👍  as I think this would satisfy the requirement to do command line install (consider Ansible, Puppet, Chef, etc). This may be impacted by #558 depending on how the update lifecycle is implemented in the Felix file install code.

Any further discussion on this issue?

**Comment by ctron** [comment]
We do have an experimental branch with Karaf now. And it does contain all the goodies Karaf has. Including file install.

I will try and document it over the next days.

**Comment by dwoodard1** [comment]
@ctron Is this issue still open or tracked elsewhere in your Karaf work? Just wondering if we can close this and/or #99 at this point?

**Comment by ctron** [comment]
This issue is independent of Karaf. And since we won't switch to Karaf for 3.0, I would like at least to provide this feature out of the box for Kura.

**Comment by MMaiero** [comment]
Since it's available as a dp in the [marketplace](https://marketplace.eclipse.org/content/apache-felix-fileinstall-package), I would close this issue for now
