### ISSUE TITLE
Retain kura build artifacts in the CI workspace available for downloads

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kura#134]
Retain kura build artifacts, especially Kura installers for various platforms, in the CI workspace available for downloads.

**Comment by MMaiero** [comment]
Since Build #570 Hudson build will retain the artifacts of Kura-snapshot builds. Following the list of .deb and .sh files available from the build page:

- kura_{version}_beaglebone-nn_debian_installer.deb 
- kura_{version}_beaglebone_debian_installer.deb 
- kura_{version}_intel-edison-nn_installer.sh 
- kura_{version}_raspberry-pi-2-nn_installer.deb 
- kura_{version}_raspberry-pi-2_installer.deb 
- kura_{version}_raspberry-pi-bplus-nn_installer.deb 
- kura_{version}_raspberry-pi-bplus_installer.deb 
- kura_{version}_raspberry-pi-nn_installer.deb 
- kura_{version}_raspberry-pi_installer.deb
