### ISSUE TITLE
[Wires] Deleting a Timer instance might stop all other Timers

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#1471]
In the current implementation the `finalize()` method of the Timer component stops the Quartz scheduler instance shared across all Timers. If a Timer is garbage collected while other instances of this component are running they will stop ticking.
A possible solution could be keeping a static counter of the active timer instances and shutdown the scheduler when the last Timer instance is deactivated.

**Comment by cdealti** [comment]
@nicolatimeus or wrap Quartz in an lazy OSGi service that would be activated on the first Timer using it and deactivated when there are no more Timers.

**Comment by amitjoy** [comment]
A timer will not be garbage collected since the shared scheduler instance will be active in all the other timer references. If the Quartz instance could have been declared with soft or weak reference, it could have been collected by the GC but currently it is a strong reference. 

I like the idea of wrapping quartz as an OSGi service that could be really helpful in managing dependencies amongst other service components.

**Comment by nicolatimeus** [comment]
I've tried the approach of crating a lazy OSGi service that wraps the scheduler. It works but the scheduler service will never be deactivated by the framework even if there are no references to it, causing a resource leak.

This is caused by the fact that the Equinox DS implementation never deactivates lazy components by default (see [here](https://wiki.eclipse.org/Equinox/RuntimeOptions#System_properties_of_bundle_org.eclipse.equinox.ds)).

I've also tried to specify the `-Dequinox.scr.dontDisposeInstances=false` runtime option to change this policy, but this caused the Timer to stop working. (the scheduler service is unexpectedly unbound by the framework with the timer component being still active, I didn't investigate the cause of this).
