### ISSUE TITLE
H2 DB: Web app and TCP server are mutually exclusive

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1513]
@nicolatimeus can we add more configuration options to enable the H2 Web app and TCP server independently?
I believe that replicating the existing settings for a another server instance would just work.

**Comment by nicolatimeus** [comment]
We can achieve this in at least 3 ways:

1. Turning the H2DbServer into a factory and keeping the metatype as it is now.
2. Creating 3 dedicated H2DbServer components, one for each mode (regular ConfigurableComponents, not factories):
   * One for Web mode
   * One for TCP/JDBC mode
   * One for PG mode
  The metatype of each of these components will look like this:
   * **db.server.enabled**: BOOLEAN
   * **db.server.commandline**: STRING
3. Keeping a single H2DbServer component (not factory) and modifying the metatype in order to allow to enable and configure each mode separately, the metatype of this component will look like this:
   * **tcp.enabled**: BOOLEAN
   * **tcp.commandline**: STRING
   * **web.enabled**: BOOLEAN
   * **web.commandline**: STRING
   * **pg.enabled**: BOOLEAN
   * **pg.commandline**: STRING

**Comment by cdealti** [comment]
1 looks cheaper in terms of work, right?

**Comment by markoer** [comment]
1 looks most configurable, but has the potential to e.g. expose the database via web 2 or more times using different options. Do you want to allow such scenarios? If yes, go for it.
3 offers the most control and least chance for abuse while still compact.

**Comment by cdealti** [comment]
@markoer we understand you point. If we go with 1 what are the testing implications?

**Comment by markoer** [comment]
I suppose the only difference would be to test that multiple ports can provide the same service concurrently  vs. that that is not possible.

**Comment by cdealti** [comment]
@nicolatimeus I also believe we should update the documentation in the Wiki to reflect the latest changes. It maybe easier if you do that now.

**Comment by cdealti** [comment]
@nicolatimeus can we close this?
