### ISSUE TITLE
The updated() method in the NetworkConfigurationServiceImpl swallows exceptions

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1562]
The updated() method in the NetworkConfigurationServiceImpl logs exceptions but doesn't provide any way of notifying user that configuration update was not successful. Possible solution is to extend the   NetworkConfigurationChangeEvent to include update status information and post this event on exception as well, but with the status of "false". We would also need to make this event visible via org.eclipse.kura.api.

**Comment by cdealti** [comment]
@ibinshtok @dwoodard1 I wonder if this requirement can be extended to all "configurable services" whose configuration can be updated. Under `org.eclipse.kura.configuration` we already have a couple of API events (not sure what they are for).

Do we want a new API event that configurable services may send to notify subscribers if the updated configuration is "valid" or not. A configuration can be valid from the Metatype perspective but not for the receiving component. For example if an Metatype attribute represents an IPv4 address a string one can legally enter "foo" in the Web UI and successfully apply the configuration. "foo" however is not valid for the component receiving (asynchronously) the updated configuration.

It's true that the receiving component may send an event upon validating the configuration but it's not forced to do that so it's not clear to me if this is very useful. For example after applying a configuration the Web UI may wait for the event and maybe display red marks on the attributes that are not valid (based on the event info). However, as the event may not be sent by the service being configured, the wait will timeout (OK, we could set a reasonably short timeout).

The event should (in order of importance) provide information on:
1. The `kura.service.pid` of the component that posted the event
2. Whether the configuration update is valid or not
3. Information on the attributes that are not valid (at least their names)
4. The "effective" configuration of the service. We know that sometimes an attribute can be left blank and its description clarifies how the service will assign a value.

The events could be like this:

Configuration is valid:
* topic: `org/eclipse/kura/configuration/ConfigValidEvent/<kura.service.pid>/SUCCESS`
* properties: the "effective" configuration or an empty dictionary is the service does not want to build it.

Configuration is not valid:
* topic: `org/eclipse/kura/configuration/ConfigValidEvent/<kura.service.pid>/FAIL`
* properties: a dictionary containing only the attributes that are not valid.

A subscriber will be able to subscribe to the following topics:

* All ConfigValidEventS: `org/eclipse/kura/configuration/ConfigValidEvent/*`
* The ConfigValidEventS of a specific kura.service.pid: `org/eclipse/kura/configuration/ConfigValidEvent/<kura.service.pid>/*`

As it does not makes much sense to subscribe to only one of `org/eclipse/kura/configuration/ConfigValidEvent/<kura.service.pid>/FAIL` or `org/eclipse/kura/configuration/ConfigValidEvent/<kura.service.pid>/SUCCESS` we could remove `FAIL` and `SUCCESS` from the topic and use a "valid flag" in the event dictionary. If this is desired, let's define the property name of the "valid flag" as a constant in the ConfigValidEvent class so that it will be well-known and not confused with the configuration attributes.
