### ISSUE TITLE
CloudClient - Add option to use the appTopic as is (not modify it) - add compatibility with IBM Watson IoT

### ISSUE THREAD

**Issue by coalpower** [eclipse/kura#1600]
My suggestion is to add the feature to disable the "encodeTopic" function in CloudClientImpl.java.
That way, we can send message using custom app with the proper topic format to IBM Watson IoT.

Here is the documentation about Watson IoT MQTT connectivity for gateways:
[https://console.bluemix.net/docs/services/IoT/gateways/mqtt.html#mqtt](url)
With a few modifications to CloudClientImpl.java, I was able to publish messages to Watson IoT.

Having this feature selectable in the web UI would be great!
Below is an extract from my own permanent modification for testing with IBM Watson IoT:
/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudClientImpl.java
(I modified 6 lines that was using fullTopic to use appTopic)

(line 134)
>     @Override
>     public int publish(String deviceId, String appTopic, byte[] payload, int qos, boolean retain, int priority)
>             throws KuraException {
>         boolean isControl = false;
>         //String fullTopic = encodeTopic(deviceId, appTopic, isControl);
>         return this.dataService.publish(appTopic, payload, qos, retain, priority);
>     }

(line 196)
> @Override
>     public void unsubscribe(String deviceId, String appTopic) throws KuraException {
>         boolean isControl = false;
>         //String fullTopic = encodeTopic(deviceId, appTopic, isControl);
>         this.dataService.unsubscribe(appTopic);
>     }

**Comment by MMaiero** [comment]
@coalpower If I've understood correctly what you are suggesting, I believe this could lead to a breaking change: it will demand to the application the definition of the full topic, while now it is only required to manage the "App Topic" that is the application specific part of the topic.

To achieve what you desire you could reference directly the DataService, instead of using the Cloud Service.
https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/data/DataService.java

**Comment by coalpower** [comment]
@MMaiero Correct me if I'm wrong but if I instantiate the DataService directly from my App, I won't be able to use the "Connect" button and I won't see the connection status from the Kura web UI (see picture attached)
![kura-cloud](https://user-images.githubusercontent.com/26559293/29788508-e24ffaee-8c00-11e7-9bf6-05c1ecb403f7.png).

**Comment by MMaiero** [comment]
Correct. But, in general, you create a cloud stack in advance and you don't need to create from scratch by your application. 

What you need is to define the properties of the stack. Then your application needs to take a reference of the corresponding DataService, instead of taking a CloudClient. In this way, you will be able to publish messages (you'll need to define the full topic by your application) and also to subscribe and receive messages.
You will also have a Cloud Service on top that you can continue to use in order to connect/disconnect or interact with the web UI.

**Comment by coalpower** [comment]
@MMaiero  At the beginning, I was testing with "org.eclipse.kura.example.publisher" and this example is using the CloudService API which doesn't work with IBM Watson IoT Platform because of the topic generated by the CloudService. Following your advice, I created my own "publisher app" based on the example but, instead of using CloudService, I use the DataService API. That way, I was able to make it work properly with IBM Watson IoT Platform. Here is my code for testing :+1: 
```
private void doPublish() {

    // fetch the publishing configuration from the publishing properties
    boolean publisher_enabled = this.m_PublisherOptions.getPubEnable();
    String typeid = this.m_PublisherOptions.getTypeId();
    String deviceid = this.m_PublisherOptions.getDeviceId();
    String eventid = this.m_PublisherOptions.getEventId();
    Integer qos = this.m_PublisherOptions.getPublishQos();
    Boolean retain = this.m_PublisherOptions.getPublishRetain();

    if (publisher_enabled) {

        // Increment the counter value
        int counterIncr = (int) this.m_PublisherOptions.getCounterIncrement();
        this.Counter += counterIncr;

        // Build the message
        // Topic format is : iot-2/type/**mydevice**/id/**device1**/evt/**status**/fmt/json
        Date timestamp = new Date();
        final String topic = "iot-2/type/" + typeid + "/id/" + deviceid + "/evt/" + eventid + "/fmt/json";
        final String payload = "{ " + "\"sentOn\": " + timestamp.getTime() + ", \"counter\": " + this.Counter + "}";

        // Publish the message
        try {
            m_dataService.publish(topic, payload.getBytes(), qos, retain, 1);
            s_logger.info("Published to {} message: {}", topic, payload);
        } catch (Exception e) {
            s_logger.error("Cannot publish topic: " + topic, e);
        }
    }
}
```
Thank you for your help!

**Comment by MMaiero** [comment]
Great! SO I believe we can close for now. Don't hesitate to reopen this issue if needed.

Best regards
