### ISSUE TITLE
Wifi configuration files should not have passwords inside

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#170]
Kura will instrument the passwords when needed

**Comment by cdealti** [comment]
@ibinshtok @MMaiero On a related topic, for Ethernet interfaces we rely on /etc/network/interfaces to configure interfaces at boot.

For wireless (WiFi, cellular) we don't. Any reason for this asymmetry?

 And if we did it and we encrypted the wireless passwords it would not work.

**Comment by ibinshtok** [comment]
Yes, it is possible to setup the /etc/network/interfaces file to launch wpa_supplicant or hostapd automatically. The respective lines are:
wpa-conf /etc/wpa_supplicant-wlan1-wpa2-eap-tls.conf
hostapd /etc/hostapd-wlan0.conf
I am using this approach for King County to provide a reliable and simple way to ensure that wireless interface is ready for the c5921 router to use. 
I think that this approach is neat, but it is less flexible since Kura will have no control on what command line parameters to pass to a supplicant or hostapd.

**Comment by MMaiero** [comment]
Closing, as from Kura 5 the wifi passwords are encrypted
