### ISSUE TITLE
[Network] WiFi channels > 11 missing in scan results.

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#173]
Howerver, the WiFi will associate on channels > 11

**Comment by cdealti** [comment]
@ibinshtok Is this really a bug? Isn't it enough to change the property in kura.properties?

**Comment by ibinshtok** [comment]
I think it is a bug. It would not be enough to modify the kura.wifi.top.channel option in the kura.properies since we have this code in the web2 (note that MAX_WIFI_CHANNEL is 13):
channelDataProvider.getList().remove(MAX_WIFI_CHANNEL - 1);
channelDataProvider.getList().remove(MAX_WIFI_CHANNEL - 2);

**Comment by cdealti** [comment]
@ibinshtok I believe changing the property worked for me. Let's fix it.

**Comment by ibinshtok** [comment]
@cdealti ok, I will work on the fix.

**Comment by ibinshtok** [comment]
all I had to do to enable channels 12 and 13 was to set the kura.wifi.top.channel configuration property in the /opt/eurotech/esf/kura/kura.properties file to 13. After that I was able to scan and connect to access point that was set to channel 13.

**Comment by cdealti** [comment]
@ibinshtok  OK. I'm closing this and adding an issue to add a documentation page for the kura.properties file.
