### ISSUE TITLE
GPIO example not working:: java.lang.NullPointerException

### ISSUE THREAD

**Issue by AhmedGhar** [eclipse/kura#1937]
java.lang.NullPointerException
[org.eclipse.kura.blink.zip](https://github.com/eclipse/kura/files/1774423/org.eclipse.kura.blink.zip)
[org.eclipse.kura.blink.zip](https://github.com/eclipse/kura/files/1774424/org.eclipse.kura.blink.zip)

Hello guys, 
I am just starting with Kura and I wanted to start with simple manipulation of the GPIOs, 
However when I run the GPIO example:
https://github.com/eclipse/kura/blob/KURA_3.1.0_RELEASE/kura/examples/org.eclipse.kura.example.gpio/src/org/eclipse/kura/example/gpio/GpioComponent.java

I have a log error: java.lang.NullPointerException
it's refering to those lines:
.....
gpioService.getAvailablePins();
.....
try {
                KuraGPIOPin p = this.gpioService.getPinByTerminal(27, KuraGPIODirection.OUTPUT,
                		KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
                p.open();
....
Any one can help me please...
PS: Do I need to install a package, Driver to start with the GPIOs ?? 

- Component affected:
  - [ ] Distribution
    - Installer: kura_3.1.1_raspberry-pi-2-3_installer.deb):
    - Platform: Raspberry pi 3
    - Kura  3.1.1 
    - openjdk version "1.8.0_151"
    - OS: Raspbian 
    - OS version: 4.9

  - [ ] Development environment: Eclipse
    - Version: Oxygene
    - Operating system: Linux
    - OS Version: 3.26.2
    - IDE Version: Oxygen.2 Release (4.7.2)
    - Host System Java Version: 1.8

**Comment by MMaiero** [comment]
Hi, 
first of all thank you for trying Kura.

I would ask you to do not cross post your issues (https://www.eclipse.org/forums/index.php/t/1092003/) otherwise it's difficult to track them down and also help other people that may have the same issue.

I believe you are not correctly getting the gpioService. Comparing your component definition in OSGI-INF folder with what defined in the provided example (https://github.com/eclipse/kura/blob/KURA_3.1.0_RELEASE/kura/examples/org.eclipse.kura.example.gpio/OSGI-INF/gpio.xml#L31), you are missing the dependency declaration for Declarative Services (DS). 

Furthermore, be careful that you are specifying a configurable component (a component that is actually configurable in its parameters from the Kura web UI) but you are not defining the configuration structure like done in the Kura's GPIO example https://github.com/eclipse/kura/blob/KURA_3.1.0_RELEASE/kura/examples/org.eclipse.kura.example.gpio/OSGI-INF/metatype/org.eclipse.kura.example.gpio.GpioComponent.xml 

Maybe you can use as a reference for your first steps with Kura the official documentation here available: https://eclipse.github.io/kura/dev/kura-setup.html

Best regards,
Matteo

**Comment by AhmedGhar** [comment]
Thank you dear for your reply, 
It works now,
I had to add the GPIOService to the Referenced Services in my OSGI-INF/component.xml
Thank you for helping
