### ISSUE TITLE
[QA] - v3.2.0 Platform QA

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1965]
Let's try using this issue to track the QA for this release. Below are the platforms listed on the Eclipse Kura website:

- Raspbian (RPi 2/3)
- Raspbian (RPi B+)
- BeableBone Black
- Fedora (RPi 2/3)
- Intel Edison
- Aarch 64

@markoer Can you provide a link to the latest QA spreadsheet?

@feclare Will you be able to perform QA on the Aarch 64 platform? We are targeting the Kura release for the end of March, but understand if the QA for the Aarch64 lags behind a bit due to the short notice.

**Comment by kartben** [comment]
What is the status of Kura for Windows? I always tell people Kura is supported on Windows but I understand it might not be true (anymore?), or at least the messaging to the community needs improving, I guess.
See eg. https://www.eclipse.org/forums/index.php/t/1092077/ - I think the fact that distributing a proper Kura installer for Windows is not possible is completely unrelated, and should not prevent to, having a tested Windows port in the Kura repository?

**Comment by markoer** [comment]
#637, #1023, #1204 are just some of the issues going against Windows support. And yes, the 'best' one is the one exposing the legal issues.

Here's the link to [Kura QA](https://eclipse.github.io/kura/assets/qa/system-test/qa_kura.ods) spreadsheet.

**Comment by markoer** [comment]
I'll use this issue to highlight the changes between release candidate builds 44 and 45, so that we can focus on those just a bit more when RC 45 is available. If there are some others, please add them (add new or update this comment).

ISSUE | RPi Raspbian | RPi Fedora | BBB
------|---------------|------------|----
factory PID cleanup (#2022, 'Another variant' part of #2015) | OK |  | OK
turning off the DHCP server and replacing it with a client (#1997) | OK |  | OK
named config (#1989) | OK |  | OK
cloud service PID validation (#1959) | OK |  | OK
search domain field removal (#1993) | OK |  | OK
drivers and assets Factory PID (#2020) | OK |  | OK
array validation (#2007) | OK |  | OK
example publisher activation (#2002, #2009, maybe also #2008) | OK |  | OK
watchdog update (#2010, #2011) | OK |  | OK
page refresh on component delete (#2014) | OK |  | OK
partial fix for #1853 |  |  | N/A
error message not being shown (#2012) | OK |  | OK
modified wrong reference to internal modem | N/A |  | N/A
create the .dp file for the gpio driver during the distrib build | OK |  | OK
maintenance fixes backporting (#1988) | N/A |  | N/A
re-enabled plain Fedora installer | N/A |  | N/A

**Comment by MMaiero** [comment]
Fedora .sh scripts are available in the workspace: https://hudson.eclipse.org/kura/job/kura-release-candidate/ws/kura/distrib/target/
I'll update the build job of both RC and release to distribute them as well (if needed, @ctron could you give us some feedback on that?).
