### ISSUE TITLE
Install/Update a bundle from the command line without restart of kura

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#1969]
There is currently no way (I know of) to install or replace a bundle from the command line (while kura is running) that will work 100% including after kura is subsequently re-started.

You can install/update via the osgi terminal but that is not persistent into the next re-start/execution of kura.

The web and mqtt interfaces both seamlessly update/install bundles in a way that is persistent.

There are many other methods of getting a bundle.dp on to a filesystem, which can be useful when a device has no route to the internet.

The command line interface SHOULD be the most trusted, it can after all kill kura entirely.

It makes sense then that there should be a way to seamlessly update/install a bundle from the command line.

**Comment by MMaiero** [comment]
Hi,
thank you for your comments and ideas.

The osgi console works on the storage area and, since we start clean, it is fully wiped at every start.
We provided a service (deployment service) that leverages the deployment admin to perform the installation outside of the storage area. Currently, this is also exposed and invokable from the cloud on specific topics.

Originally, the command line interface was not meant for installing bundles due to the fact that you could install them leveraging the web ui for a local installation and you had the DEPLOY cloudlet for remote installation. 

In any case, if you feel that this could be an appreciated improvement, feel free to contribute the code to the community and to the project!

Best regards,
Matteo

**Comment by cdealti** [comment]
closing
