### ISSUE TITLE
[Bluetooth] add compatibility with Bluez-5.x

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#209]
Currently Kura supports only Bluez-4.101.
In order to support also Bluez-5.x, the BluetoothGattImpl class must be modified to
- correctly parse the connection successful string in gatttool;
- detect the disconnect event;
- check the connection.

**Comment by pierantoniomerlino** [comment]
Tests:
- [ ] Bluez 4.101
- [ ] Bluez 5.23
- [ ] Bluez 5.33
- [ ] Bluez 5.39

**Comment by ccustine** [comment]
👍  I tested your branch and this seems to be working better than my quick fixes. I am running some longer tests with multiple devices connected but I think this fix looks good.

**Comment by pierantoniomerlino** [comment]
@gavinying 
Have you had a chance to take a look on it?
Thank you.

**Comment by gavinying** [comment]
I haven't tested yet, but the code looks good. I hope could find some time to test it over weekend :)

Maybe only one thing that I want to point out here, 

    else if (checkString(line.toLowerCase(), CONNECTED)) {
        m_ready = true;
        m_connected = true;
    }

Shall we change to 

    else if (checkString(line.toLowerCase(), CONNECTED)) {
        m_connected = true;
        m_ready = true;
    }

Because in multi-thread context, once m_ready set to true in thread A, the other thread B pending in connect() may instantly resume to return m_connect status, which may haven't been set to true yet in thread A. Although it seldom happen, but theoretically it could happen.

**Comment by gavinying** [comment]
Just tested on bluez 5.39, works fine.

**Comment by pierantoniomerlino** [comment]
@gavinying @ccustine 
Thank you very much for the tests and comments.
I agree on the modification for the multi-thread context.

**Comment by pierantoniomerlino** [comment]
@cdealti 
Could you please take a look at this PR?

**Comment by MMaiero** [comment]
Closed as PR #217 merged to develop.
