### ISSUE TITLE
ChannelDescriptor are cached too aggressively and/or need a way to invalidate the channel descriptor for a Driver

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#2146]
It looks like the Driver#getChannelDescriptor() method is only called during the initial creation of a particular driver (or when it is re-loaded from the preferences), which I don't think is right. The available channels and/or their topology might be depending on the configuration of the driver.
 
I looked at an API to 'invalidate' the channel descriptor of a particular driver but I don't believe there is anything publicly available - so I think we'd need either that, or not cache the results of getChannelDescriptor() so that whenever one starts trying to configure the channels of a particular asset, it uses a 'fresh' channel descriptor.

**Comment by kartben** [comment]
Ping?

Having put a bit more thoughts into this, my impression is that the Driver API might be missing a way to register a listener notified when the configuration of the driver changes. Such an API would make it easy to keep the channel descriptor up-to-date in the BaseAsset class

**Comment by LucaDazi** [comment]
@kartben do you have a specific use case for such a behavior?
The original idea of the ChannelDescriptor was just to have a way to expose the specific configuration of a driver's channel, and it is meant to be static on the driver, because variations of the channel descriptor may lead a driver to be no more compatible with the assets it is assigned to.

The configuration of the assets linked to a driver is stored in the assets themselves, so changing the channel descriptor dynamically is not a great idea, imho.

Moving the configuration of all the channels inside the configuration of the drivers, and then linking the assets to the specific channels may be a solution to this, but I'm not sure this is what you are trying to achieve.
