### ISSUE TITLE
[Camel] Do we need a Camel API in the org.eclipse.kura.api bundle?

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#221]
@hekonsek in Kura we package APIs in the ``org.eclipse.kura.api`` bundle. Typically, implementation bundles do not export API packages and where they do that it's only for internal use by other Kura bundles.

For Camel we don't have anything in the API bundle.

It looks to me that the Camel "API" is [CamelRouter](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.camel/src/main/java/org/eclipse/kura/camel/router/CamelRouter.java). Well, it's not actually a service interface but it's looks to me that ``CamelRouter`` plays a role similar to that of [Cloudlet](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/cloud/Cloudlet.java) which is in the Kura API bundle but it's not a service interface but a base class that needs to be extended.

I'm not sure what to do for Camel

**Comment by cdealti** [comment]
This issue is postponed and will be addressed in Kura-2.1.0

**Comment by cdealti** [comment]
@hekonsek  I believe we need to extract a Java interface from the ``CamelRouter`` and add it to the ``org.eclipse.kura.api`` bundle. Let's rename the current ``CamelRouter`` to ``CamelRouterImpl`` and reserve ``CamelRouter`` for the interface.

 Consumers will not extend ``CamelRouterImpl``. Instead they will request a new ``CamelRouter`` to a ``CamelService`` via a ``newCamelRouter`` factory method.

It's more in the OSGi spirit for consumers to use an interface instead of exposing the details of an implementation.

Also the name of the ``org.eclipse.kura.camel`` bundle and the names of the packages need to be refactored.

For implementation bundles we are starting following the convention of adding a **.provider** suffix.

For internal packages we are following the [Eclipse naming convention](https://wiki.eclipse.org/Naming_Conventions)
so the packages in the ``org.eclipse.kura.camel.provider`` bundle would start with ``org.eclipse.kura.internal.camel``.

**Comment by ctron** [comment]
I would strongly recommend against adding another technology to the "org.eclipse.kura.api" bundle. It already seems overloaded with functionality to me, and the idea of OSGi is to keep thing modular. Adding every technology in Kura to the "api" bundle will simply create a "super bundle".

Right now (with the PR #365) it is possible to simply add "Camel" as a dependency without triggering any service by using the `org.eclipse.kura.camel` bundle. It providing the basic building blocks for Camel in Kura.

Dropping in the `org.eclipse.kura.camel.xml` bundle registers a service which allows Camel to be simply configured using XML. Currently it is hard to use due to various restrictions on the Web UI 2 module. (also see #338).

The current architecture of base classes allows you to either create your own implementation, your own implementation based on Camel/Kura "best defaults" or simply provide Routes using Java, XML or through the configuration service.

I see no benefit in having a `CamelRouterBuilder` service. In fact you will loose the whole customization which you have now. Therefore this should also not be "internal", since it really is considered a building block for others.

I also would be good to have some sort of document explaining all conventions and linking to them in the `CONTRIBUTING.md` file.

**Comment by cdealti** [comment]
> I would strongly recommend against adding another technology to the "org.eclipse.kura.api" bundle. It already seems overloaded with functionality to me, and the idea of OSGi is to keep thing modular. Adding every technology in Kura to the "api" bundle will simply create a "super bundle".

Well, retrospectively I would agree on this. The API should be ideally split in multiple bundles.
However, having API bundles, **only** containing interfaces and POJOs, still looks a good idea to me.
Note that, even with the monolithic API bundle there will be no issues in adding another API because this does not add any new dependencies (take a look to the Import-Package header in the API MANIFEST).

In Kura, apps are only expected to import packages starting with ``org.eclipse.kura.api``. I don't think it really matters if these packages are in a single bundle or split in multiple bundles.

> Dropping in the org.eclipse.kura.camel.xml bundle registers a service which allows Camel to be simply configured using XML. Currently it is hard to use due to various restrictions on the Web UI 2 module. (also see #338).

#338 moved to **Backlog**.

> The current architecture of base classes allows you to either create your own implementation, your own implementation based on Camel/Kura "best defaults" or simply provide Routes using Java, XML or through the configuration service.

I'm not saying I want to get rid of this. We wanted and planned this since the beginning.
I'm just proposing to avoid extending a class (exposing its implementation) and prefer obtaining an instance through an OSGi service (a Java interface).

> I also would be good to have some sort of document explaining all conventions and linking to them in the CONTRIBUTING.md file.

I agree. I need to check if we already have an issue for this.

**Comment by ctron** [comment]
I do think it makes quite a big difference. If you offer the API, and if you put this into the "super bundle" then you always offer it, you should also offer an implementation. But if you want to make a distribution without providing Camel, then you are lost, since you don't have any chance to configure a system which is simply leaving out that API.

And then just imagine you want to make a V2 of that Camel API? Again you will run into issues unless you add the version number into your package namespace.

I really do think that splitting off modules is the right way to go.

Maybe you can explain why do you want to avoid extending classes? Right now it is possible to extend as necessary. Re-working this would mean you introduce some interface like `CamelContextCustomizer` which will be allowed configure the internal state. Followed by an abstract implementation of `XmlCamelContextCustomizer` which performs the customization based on XML data.

However, as it is now, the extended classes build a class hierarchy based on the original camel classes. And therefore also a dependency tree based on that. If a camel bundle gets restarted the whole dependency tree will get restarted. If you introduce a builder/factory service, then this will not happen and you will be left over with stale classes unless you implement again some service tracking for your implementation.

**Comment by ctron** [comment]
I think we can close this one as we agreed in the F2F meeting that Camel will not be placed in the "org.eclipse.kura.api" bundle.

**Comment by cdealti** [comment]
Let me just keep this open to make sure we add this bundle to the Javadoc generation.

**Comment by ctron** [comment]
@cdealti I just tried to find where the Javadoc is being generated. However I cannot find anything "javadoc" related in the build. Maybe you can point me into the right direction. Thanks.

**Comment by cdealti** [comment]
@ctron it should be under ``target/site/apidocs`` in the parent project (the one with ``manifest_pom.xml``)

**Comment by ctron** [comment]
Ok, so then it already is being generated.

**Comment by ctron** [comment]
The actual content will be in the PR which comes after the upgrade to Camel 2.17.0

**Comment by ctron** [comment]
PR #508 contains some updated javadoc

**Comment by cdealti** [comment]
@ctron Can we close this?

**Comment by ctron** [comment]
:+1:
