### ISSUE TITLE
OpcUaDriver can not connect if OPC UA Server started after kura and can not reconnect after disconnect by exception

### ISSUE THREAD

**Issue by spnettec** [eclipse/kura#2241]
I created this patch

[OpcUaDriver-reconect.txt](https://github.com/eclipse/kura/files/2393984/OpcUaDriver-reconect.txt)

**Comment by nicolatimeus** [comment]
@spnettec can you please post more information describing the connection failure like the logged exception?

It should be possible to implement some connection monitoring logic without modifying the driver code by using Kura Wires:

* Create a Timer that ticks at a fixed rate (e.g. 10 seconds like in your patch).
* Connect it to an OPCUA asset that reads any variable from the server.
* Make sure that the session timeout parameter in driver configuration is greater than the timer tick interval to avoid session expiration.

This should be enough to make the driver reconnect on failure.

How are you using the driver? polling using wires? in event driven mode setting the "listen" flag?  reading "occasionally" (not on a regular basis) using the drivers and assets ui or through the cloud?

**Comment by spnettec** [comment]
@nicolatimeus 

>How are you using the driver? polling using wires? in event driven mode setting the "listen" flag? reading "occasionally" (not on a regular basis) using the drivers and assets ui or through the cloud?

Yes. I use this driver in event driven mode setting the "listen" flag

![image](https://user-images.githubusercontent.com/1769060/45741034-32fe2e80-bc29-11e8-951e-9b677d14f5f3.png)


![image](https://user-images.githubusercontent.com/1769060/45741120-62ad3680-bc29-11e8-9d63-8bf5b76f91ee.png)



If i start the kura emulator in eclipse debug pattern and then start prosys-opc-ua-simulation-server. There no publisher output and no any exception in eclipse debug console.


![image](https://user-images.githubusercontent.com/1769060/45741410-1282a400-bc2a-11e8-8d8e-d6753900cc2c.png)


If i refresh the data the connection would be established.

![image](https://user-images.githubusercontent.com/1769060/45741687-cd12a680-bc2a-11e8-97d2-64c6e9e83400.png)

Sometimes i debugging code would broken the connection and could not reconnect agin.

**Comment by spnettec** [comment]
If you want to reproduce this issue just use graph like this:

![image](https://user-images.githubusercontent.com/1769060/45742169-f1bb4e00-bc2b-11e8-80ba-3b090c984d2c.png)

Remove the subscriber. I use this to debug typed json.

**Comment by nicolatimeus** [comment]
Yes, this is known behaviour, the driver currently will not try to reconnect on connection failure if it is used in listening mode only.

This is generally not a problem in polling mode because a connection attempt will be made at every read/write, but if the driver is used in event driven mode only, it will not try to reconnect.

When we added support for event driven mode in the driver, we decided to postpose the implementation of some connection monitoring logic, since this this logic can be easily implemented by adding to the graph another timer and an asset with a single channel in polling mode as suggested in my previous comment.
