### ISSUE TITLE
Bundle creation for eclipse Kura 

### ISSUE THREAD

**Issue by YassineElyk** [eclipse/kura#2275]
Hello everyone,

I'm starting with kura development and I would like to know how you guys create OSGI bundles for kura? and what should I do to include non OSGI projects like for example in my case eclipse Leshan, that is provided as a maven project in github, as a bundle that can be used by other bundles, or as an inner dependency in a particular bundle?

**Comment by dwoodard1** [comment]
@Yalayak We are in the middle of releasing a new version of Kura, which is why the response to your question has been slow. 

We have getting started documentation on Kura [here](http://eclipse.github.io/kura/dev/kura-setup.html). I would recommend going through the tutorial and reporting any issues you have.

There are several forum posts on embedding standard JAR files in an OSGi bundle. One example is [here](https://www.eclipse.org/forums/index.php/t/1083611/). You can also see how Kura embeds the Eclipse Paho project [here](https://github.com/eclipse/kura/tree/develop/kura/org.eclipse.kura.core).

**Comment by MMaiero** [comment]
Hi @Yalayak, can this issue be closed?

**Comment by YassineElyk** [comment]
yes go ahead
