### ISSUE TITLE
Plugin 'jdk.dio' does not include package 'jdk.dio.pwm'.

### ISSUE THREAD

**Issue by jorge-recio** [eclipse/kura#2326]
**Describe the bug**
Is impossible to use the package 'jdk.dio.pwm' when creating a plugin for Kura because it is not exported in the plugin 'jdk.dio'.

**To Reproduce**
1. Create a plugin project.
2. Go to the plugin manifest.
3. Click on the dependency tab.
4. Go to section Imported Packages. 
5. Search for package 'jdk.dio.pwm'.

**Expected behavior**
The package should appear because is part of 'jdk.dio' implementation.

**Screenshots**

**Development Environment (please complete the following information):**
 - OS version: Windows 10
 - Additional info: It should happen in all environments.

**Additional context**
The problem should be in the way of creating the plugin 'jdk.dio' because the package 'jdk.dio.pwm' is not included in the plugin.
In the source code the package is included in the 'target-platform/jdk.dio-parent' project in folder the 'target-platform/jdk.dio-parent/src/dev/src/share/classes/jdk/dio/pwm' but is not included in the 'target-platform/jdk.dio-parent/jdk.dio' child project where should be.

A similar packaging of 'jdk.dio' have been created including 'jdk.dio.pwm' package, see [here](https://jar-download.com/artifacts/io.earcam.wrapped/org.openjdk.dio/).

Thanks in advance.

**Comment by LucaDazi** [comment]
Hello,
jdk.dio has never been updated since its first introduction in Kura.

Inside the target-platform folder in the code base you'll find the source code for the modified version of jdk.dio we are using. We had to modify the original library, both for the Java code and the native libraries, starting from version 1.0.0.

A jdk.dio version with the jdk.dio.pwm package exported was released later, in version 1.1.0

An update to the current version of jdk.dio in the Kura code base would be a really welcome contribution.

**Comment by jorge-recio** [comment]
Thanks for the quick response.
I still think that in Kura develop branch threre is a version of jdk.dio.pwm package in folder 'target-platform/jdk.dio-parent/src/dev/src/share/classes/jdk/dio/pwm' but somehow it is not included in binaries.
I have checked for differences between source code in jdk.dio and jdk.dio-parent, both have the same package structure and both include jdk.dio.pwm package; differences appear to be minimal.
I have not much time recently and no experience building libraries with native code, but I will try build jdk.dio library and make a PR to include it in Kura.
I am worried about how to test those packages integrated to Kura.
