### ISSUE TITLE
Variable replacement in topic string does not work anymore in new Kura 4 Cloud Publisher

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#2448]
In a Wires graph, we use a javascript filter to decode the data received from lora sensors, and we add a string metric named "mote" that represents the name of the channel (the sensor) to add it at the end of the general topic:

the javascript filter =
var outRecord = newWireRecord()
outRecord.assetName = newStringValue(record.assetName.getValue())
**outRecord.mote = newStringValue(prop)**

and in the publisher
Application.topic = Motes/**$mote**

in Kura 3 the result is:
topic :#account-name/#client-id/Lora/Motes/**Adeunis**

but in Kura 4 with the new publisher structure the result is:
topic :#account-name/#client-id/Lora/Motes/**$mote**

The $mote variable is not anymore replaced by the real value. It should be noted that only the $assetName variable is correctly replaced.

**Comment by ghost** [comment]
looking at the code base it seems that only 'assetName' is taken over from wireRecordProp as property in the kuraMessage:

https://github.com/eclipse/kura/blob/f6e982a24e742ce4b7ae37d3aeb0e66fe8798705/kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/publisher/CloudPublisher.java#L294-L301

If i understand the code correctly that is the reason why the replacement does not work as expected: 

https://github.com/eclipse/kura/blob/f6e982a24e742ce4b7ae37d3aeb0e66fe8798705/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/publisher/CloudPublisherImpl.java#L174-L190

Is this the expected behavior or is it just a bug?
