### ISSUE TITLE
WebConsole | Password restrictions are not working

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2516]
**To Reproduce**
1. Go to WebConsole service item
2. Set password restrictions (minimum characters, require digits and/or other restrictions)
3. Apply and confirm changes
4. Try to set text without digits, for example, "text" for password
5. Apply and confirm changes

**Expected behavior**
Should not be able to text without digits if you tick "require digits" restriction 

**Target Environment**
 - Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux

**Comment by MMaiero** [comment]
@nicolatimeus Could you please check this?

**Comment by nicolatimeus** [comment]
The enforcement of password strength for now is enabled only for Wifi Access Point mode password. Are you referring to that field or to other password fields? 

The password strength requirements are not enforced to other fields for now since this would require some changes to enable distinguishing between fields for defining a new password (like for the access point mode) or just providing a password (for example the password for connecting to an OPCUA server or for connecting to a wifi access point in station mode). Password restrictions do not make sense in the latter case.

**Comment by mstankovic** [comment]
@nicolatimeus Sorry, my bad. i thought this is related to device's web console password since it's on the same page as fields for changing username/password. It's not clearly and it's not intuitive that it refers to wifi (access point mode) password.

**Comment by nicolatimeus** [comment]
I agree that the current implementation of the feature is a bit confusing.
It is still a work in progress, i think that before next release we will discuss about extending the support for password strength restrictions to other fields of the web and/or improve the configuration section of the web console.
