### ISSUE TITLE
Data encoded as base64 in byte array value type 

### ISSUE THREAD

**Issue by DhruvilDhanani** [eclipse/kura#2543]
In "Drivers and Assets" component, While reading the byte array getting the result as a base64 encoding scheme.

For example,Configuration  in "Drivers and Assets" is as per following:

In assets configuration: [Input]
- type : READ
- value.type : BYTE_ARRAY [Input : new byte[]{1,2,3}]

In assets data: [Output]
- Value : AQID

**Expected behavior**
Value : {1,2,3}

**Target Environment**
KURA 3.2.0  

#1591 In this issue there is no any description available.

**Comment by nicolatimeus** [comment]
Before #1591 byte arrays were printed using the `java.lang.Object.toString()` method, so a byte array was displayed as something like `byte[]@aabbccdd`, which is a bug. This also implies that before #1591 it was not possible to perform a write to a byte array channel using the web ui.

The representation you propose is similar to the `java.util.Arrays.toString(byte[])` method (or maybe a modified version that prints unsigned values). 

If i remember correctly we compared formats similar to the one that you proposed with base64 before #1591 and we choose base64 because it is a standard format, it is compact and there are plenty of tools available for converting from/to raw data (e.g. `base64` command line utility, web based applications available online), moreover it is already used in other Kura components/protocols (e.g. ASSET-V1 cloudlet).

**Comment by DhruvilDhanani** [comment]
Hi @nicolatimeus, 
Thanks you for your answer. 

I am closing this issue.
