### ISSUE TITLE
DHCP client does not detect network IP changes

### ISSUE THREAD

**Issue by kandrej** [eclipse/kura#2578]
**Describe the bug**
DHCP client does not detect network IP changes. In case of a very long lease time it could take days for the DCHP client to request a new valid IP address.

**To Reproduce**
1. Connect the board on a router (IP address 192.168.1.1 subnet mask 255.255.255.0)
2. Boot the board
3. DHCP client acquires an IP (eg. eth0 IP 192.168.1.100)
4. Change the router network settings to IP address 192.168.2.1 subnet mask 255.255.255.0
5. DHCP client is stuck with IP 192.168.1.100 and does not acquire a new IP address until the lease ends

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3B+
 - OS version: Linux raspberrypi 4.19.75-v7+ #1270 SMIP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
 - Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
@kandrej As far as I understand, you have changed the configuration of the DHCP server and Kura updates its IP address after a very long time. The expected behavior is that the IP address would be updated after half of the lease time. Of course it depends on when the DHCP server was changed compared the lease time, but typically the IP address will not be updated immediately. 
In [1] and [2] it is explained how it should work.

[1] https://lazyadmin.nl/home-network/dhcp-lease-time/
[2] https://community.infoblox.com/t5/DNS-DHCP-IPAM/DHCP-server-behavior-when-updating-the-DNS-servers-info-in-the/td-p/12962

**Comment by kandrej** [comment]
The DHCP client works as it should, however it think if the link is dropped and then reestablished it should renew or reacquire a new IP. 

Usually every OS reacquire a new IP as soon as the cable is plugged. In my case, the home router reboots on configuration changes dropping the link. When the router boots every device has a new IP except those running Kura

**Comment by pierantoniomerlino** [comment]
@kandrej Ah ok, thank you for the clarification.

The network monitor in Kura runs every 30s, so I think that if the change is less than that period, the configuration change is lost (at least until the lease time expiration).
What happens if you unplug the cable for more than 30s and than replug it (of course with dhcp server changes)?

If so, it's not a good behavior...

**Comment by kandrej** [comment]
@pierantoniomerlino Ok, unplugging the cable for a longer period helps solving the problem.

Maybe the network monitor should also check **/sys/class/net/{interface}/carrier_changes**. If the number changes it could restart the DHCP client

**Comment by MMaiero** [comment]
@kandrej It seems a good idea. Maybe there is space for a PR?
