### ISSUE TITLE
Maven failure when dev-env isn't built

### ISSUE THREAD

**Issue by lmarshall-eth** [eclipse/kura#262]
When building without dev-env, for example with:
mvn -f pom_pom.xml -Pweb,raspberry-pi-2
the staging/target-definition directory isn't created.
This causes a build failure for the new maven archetype module.

**Comment by dwoodard1** [comment]
@cdealti This is not a trivial fix. The archetype portion of the build relies on the target platform generated by the dev-env profile. I suggest postponing this until after the 2.0.0 release as all CI builds use the dev-env profile.

@lmarshall-eth your RPI2 installers were still generated even though the build failed. The archetype creation is the last step in the build.

**Comment by cdealti** [comment]
@dwoodard1 any updates?

**Comment by dwoodard1** [comment]
I need to look into this again. The archetype module can't build unless the target-platform has been created, hence the dependency on dev-env. I will likely just move the archetype module into a profile. I will try and give it a look today.

**Comment by MMaiero** [comment]
@dwoodard1 Do we need to keep this issue open? Or we close it and, eventually, open another for the tools and dev-env correlated profiles?

**Comment by dwoodard1** [comment]
@MMaiero I think close this and we can review later. This would only be an issue if someone is specifically trying to build the archetypes and doesn't use -Ptools,dev-env. I would also like to investigate using PackageDrone to collect the target-platform instead of getting it from the build. This may be the best solution, but probably a low priority item at the moment.
