### ISSUE TITLE
Login With Certificate Possible Although Keystore Path Missing? 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3193]
If user deletes the certificate Keystore path from the web UI and saves changes, it is still possible to login with a certificate - is this the desired behaviour? I would expect that if the path to keystore is incorrect or missing, login with certificate should not be possible. 
I have tried deleteing browser cache, history and data, so browser was clean after the keystore path has been deleted. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service, delete the HTTPS Keystore path 
3. Wait fr process to finish, delete browser's cache and data
4. Logout and try to login with certificate again. 

**Expected behavior**
See above. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I have checked this issue and now Kura reports an error if user wants to save empty keystore path (Screenshot No. 1). The only problem is that the fields keystore path and password are not labeled with asterix as mandatory and also not labeled red when empty (as all other fields when they do not contain valid parameters). 

**Screenshot No. 1:** 
![Screenshot 2020-12-11 at 14 33 40](https://user-images.githubusercontent.com/15121999/101910486-478ac080-3bbf-11eb-80e5-918f37cc5c61.png)

**Screenshot No. 2:**
![Screenshot 2020-12-11 at 14 35 25](https://user-images.githubusercontent.com/15121999/101910501-4a85b100-3bbf-11eb-9a51-ff4060b87199.png)

**Comment by nicolatimeus** [comment]
Yes, the keystore path  and password fields are currently not marked as required in the metatype and for this reason they are not highlighted in red and have no asterisk. 
They are currently defined as optional so that the user is not forced to fill them if HTTPS is disabled.

The Console section has some custom conditional validation logic executed when the apply button is pressed, this is not present in the other sections like generic services config ui.

Having the fields marked in red only if HTTPS is enabled is possible by adding more custom code. The alternative is marking them as required in the metatype, in this case the user must fill them even if HTTPS is disabled.

**Comment by LeoNerdoG** [comment]
Hey, thanks for the detailed answer. I guess that this is then desired behaviour? Should we close this issue or leave it open and re-mark it as an "enhancement" or "good to have" or something similar? I think it is not a P1 anymore.
