### ISSUE TITLE
Selecting a different CloudPublisher Target  in the Publisher Wires Component stops the publishing processing

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kura#3197]
**Describe the bug**
In a Wires Graph, a Publisher component is configured to use a given CloudPublisher Target.
In the Wire Graph web UI, when switching to another CloudPublisher Target and applying those changes, the Wires graphs stop publishing data.

**To Reproduce**
1. Create a Wires Graph with a Publishing component.
2. Create an additional Publisher on the same Cloud Connection (I used an Azure SaaS Connection)
3. In the Wires graph, edit the configuration of the Publishing component and switch to the new CloudPublisher Target and Apply changes.
3. By checking the log, the Wires graph stopped publishing data upstream.
4. A restart of Kura, restores the correct behavior and the publishing resume to the new CloudPublisher Target

**Target Environment (please complete the following information):**
 - Kura on Docker with Eurotech Cloud Connector for Azure IoT Hub 
 - Kura 4.1.0

**Comment by marcellorinaldo** [comment]
I was able to recreate the issue on Kura 4.1.0. As mentioned, restarting Kura restores the correct behavior.

On Kura 5.0.0 this issue seems to be resolved: changing the target in any of the created publisher components works (also if the publishers are on different cloud connections); no need for reboot.

**Comment by MMaiero** [comment]
Closing as solved in Kura 5
