### ISSUE TITLE
Snaphot_0 Firewall rules are not processed by Kura

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#3385]
**Describe the bug**
In the snapshot_0 we add some rules for a second Ethernet port and they are simply ignored. So we need to add the rules manually.

Some rules for ports seems to be generated automatically like opening the ports for network 10.234.0.0/16 that is creating a security hazard.

**To Reproduce**
Here is the snapshot_0 firewall property
<esf:properties>
	    <esf:property array="false" encrypted="false" name="firewall.open.ports" type="String">
                <esf:value>22,tcp,,,,,,#;443,tcp,,eth0,,,,#;443,tcp,,wlan0,,,,#;4443,tcp,,eth0,,,,#;4443,tcp,,wlan0,,,,#;1450,tcp,,eth0,,,,#;1450,tcp,,wlan0,,,,#;502,tcp,127.0.0.1/32,,,,,#;53,udp,,eth0,,,,#;53,udp,,wlan0,,,,#;67,udp,,eth0,,,,#;67,udp,,wlan0,,,,#;8000,tcp,,eth0,,,,#;8000,tcp,,wlan0,,,,#;53,udp,,eth1,,,,#;63,udp,,eth1,,,,#;443,tcp,,eth1,,,,#;4443,tcp,,eth1,,,,#</esf:value>
            </esf:property>
	    <esf:property array="false" encrypted="false" name="firewall.port.forwarding" type="String">
                <esf:value></esf:value>
            </esf:property>
	    <esf:property array="false" encrypted="false" name="firewall.nat" type="String">
                <esf:value></esf:value>
            </esf:property>
	</esf:properties>

**Expected behavior**
All rules for Eth1 are not executed by Kura

**Screenshots**
See attached screenshot
![Capture](https://user-images.githubusercontent.com/30366677/119352853-79da3700-bca2-11eb-9a80-12aa8dba04ea.PNG)

**Target Environment (please complete the following information):**
 - Board IMX6
 - OS version: Linux 5.4

 - Additional info: 

**Additional context**

**Comment by pierantoniomerlino** [comment]
@sterwen Indeed the firewall rules in the snapshot are not directly applied to the system. When a rule is filled from the webUI, this is stored in the snapshot and saved in the filesystem. However, only the ones in the filesystem are re-applied at the startup. So, if you add a rules from the snapshot, not using the webUI, it is simply lost.

I think that we'd change this behavior since the snapshot is the source of truth for ESF, not the configuration files on the filesystem...

Edit: it's not totally true... the `FirewallConfigurationServiceImpl` doesn't apply the snapshot (a.k.a. the properties) during the activation. But if you apply a snapshot from the webUI, the rules are parsed and applied.

**Comment by sterwen** [comment]
@pierantoniomerlino ok, thanks for the feedback, at least this is a clear explanation. We will look to add these rules to Linux additionally as a stop gap solution.
What about the open parts ? Like 10.234.0.0/16. That should need to be removed or is there a specific reason to authorize this BIG subnetwork.

**Comment by pierantoniomerlino** [comment]
@sterwen We're trying to fix the firewall behavior in #3396.
Regarding the 10.234.0.0, indeed, I think that can be removed.
