### ISSUE TITLE
Kura 2.0.0 distribution for Raspberry-Pi includes emulator.gpio instead of linux.gpio

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#373]
The distribution package for the Raspebrry-Pi does not include the org.eclipse.kura.linux.gpio bundle.
It uses instead the org.eclipse.kura.emulator.gpio bundle.

**Comment by MMaiero** [comment]
The bug is related to the build process: the jdk.dio dependency is a workswith dependency that cannot be included in the hudson build. For this reason we will need an extended version built externally that will include the jdk.dio and the linux.gpio bundles

**Comment by dwoodard1** [comment]
The jdk.dio library was approved [1] for distribution with Eclipse, it can be part of the standard build.

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9194

**Comment by cdealti** [comment]
Isn'it a Workswith dependency?
Ciao,
  Cristiano
________________________________
Da: dwoodard1 <notifications@github.com>
Inviato: mercoledì 3 agosto 2016 20.21.17
A: eclipse/kura
Oggetto: Re: [eclipse/kura] Kura 2.0.0 distribution for Raspberry-Pi includes emulator.gpio instead of linux.gpio (#373)


The jdk.dio library was approved [1] for distribution with Eclipse, it can be part of the standard build.

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9194

-

**Comment by dwoodard1** [comment]
Originally yes, but it was later changed to fall under GPL+CPE. Read through the comments and you will eventually see where we received approval from the Eclipse board to distribute with Kura.

**Comment by cdealti** [comment]
Thanks Dave. I missed that update.


Ciao,

  Cristiano

________________________________
Da: dwoodard1 <notifications@github.com>
Inviato: mercoledì 3 agosto 2016 22.44.42
A: eclipse/kura
Cc: De Alti, Cristiano; Comment
Oggetto: Re: [eclipse/kura] Kura 2.0.0 distribution for Raspberry-Pi includes emulator.gpio instead of linux.gpio (#373)


Originally yes, but it was later changed to fall under GPL+CPE. Read through the comments and you will eventually see where we received approval from the Eclipse board to distribute with Kura.

-

**Comment by MMaiero** [comment]
ok, so we could remove the dio-skip profile from the production build?

**Comment by MMaiero** [comment]
I've modified the build. Now it seems to have the correct gpio packages
