### ISSUE TITLE
Cloud connections units tests for custom component

### ISSUE THREAD

**Issue by davide-prade** [eclipse/kura#4200]
I would need to test a bundle that handles connections to multiple Kapua clusters according to custom logics.
I would like to run these tests along the lines of `org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactoryTest`.
Unfortunately, however, the `org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactory` class is not exposed in the related POM.

How can I then test the new bundle, creating the relevant configurations if I cannot easily use the `DefaultCloudServiceFactory` class?

I have considered the following options, but none of them convince me:
 * modify Kura while maintaining a different POM;
 * mock all possible calls to "simulate" the behavior of `DefaultCloudServiceFactory`;
 * test only a narrow subset of the functions of the new component that handles connections.

Thank you!

**Comment by MMaiero** [comment]
@nicolatimeus Any thoughts on this?

**Comment by nicolatimeus** [comment]
Hi, sorry for the late reply.

`org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactoryTest` works because it is an OSGi fragment [1], and therefore has access to all of the classes of its host bundle, even if they are not exported. I think that you can use the same approach if you want to access  `org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactory` directly.

An alternative can be creating an OSGi integration test instead of an unit test. That kind of test allows you to bring up an OSGi runtime during the build and use `org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactory` through its publicly exported service interfaces (`org.eclipse.kura.cloudconnection.factory.CloudConnectionFactory`).
Unfortunately we don't have an example for an integration test that uses CloudConnectionFactory.. You can use as a reference the other integration test in the codebase, their code is in the `src/main/java` folder (not `src/test/java`) of the projects under `kura/test`, for example [2].

[1] https://github.com/eclipse/kura/blob/a195db2e3aa95d31a216856285439334e04a9b36/kura/test/org.eclipse.kura.core.cloud.factory.test/META-INF/MANIFEST.MF#L21
[2]
https://github.com/eclipse/kura/blob/develop/kura/test/org.eclipse.kura.core.test/src/main/java/org/eclipse/kura/core/test/MqttDataTransportTest.java

**Comment by davide-prade** [comment]
Thank you very much for your reply.
As soon as I have some time I will try.
