### ISSUE TITLE
Upgrade Equinox to 3.11 and use Java 8 a minimum requirement

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#460]
The current Equinox version (3.8.1) does not support Java 8.

Equinox should be upgraded to a more recent version

**Comment by scottslewis** [comment]
FWIW it does not have to be equinox 3.11 to support Java8 EE.   It could be org.eclipse.osgi 3.10.100 (mars release) as well.

**Comment by ctron** [comment]
But what would be the benefit over using 3.11?

**Comment by scottslewis** [comment]
The only benefit would be if some Kura adopters were able to adopt older versions of equinox, but not be ready for using 3.11 yet   Actually, if your consumers are like ECF's then probably what is more important than the equinox version is the OSGI framework version...for example:  v5 (lunaI think), v6 (mars and Neon).   We have some consumers for example that want to use on Felix/R5, and so they would actually prefer to use equinox R5 I think rather than OSGi R6 version.  That way they can be prevented from using the OSGi R6 features inadvertantly.

But that's probably a minority view, and for most adopters they would probably like the latest released version.

That actually leads me to another question though:   Any plans to allow use of Felix and/or other framework impls?   Your question of me wrt ECF sort of makes me think that you are thinking of that.   FWIW, it's not that hard as long as one is conscious of the spec version provided by the framework impls.

**Comment by ctron** [comment]
Migrate to Equinox 3.11 and set Java 8 as a minimum requirement for Kura.

I think it would be a good idea to put the minimum requirement in the README.md file?!

**Comment by ctron** [comment]
I think we can close this one as we achieved this in 3.0.0
