### ISSUE TITLE
Fix Sonar build step

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#519]
Currently the sonar build step on the kura-develop [1] build job fails.

```
Sonar analysis completed: UNSTABLE
```

This should be fixed.

[1] https://hudson.eclipse.org/kura/job/kura-develop/

**Comment by dwoodard1** [comment]
Yep, this is a know problem. I thought we had an issue tracking this, but I guess not. One known issue is that we have JUnit tests failing because we are pointing to an MQTT server outside of the Eclipse domain. We just need to use iot.eclipse.org.

@cdealti I just noticed we have duplicate test code in [1]. Do you know why? The tests appear to be identical. I was going to address this issue, but noticed the duplicated code.

[1] https://github.com/eclipse/kura/tree/develop/kura/org.eclipse.kura.core.test/src

**Comment by cdealti** [comment]
@dwoodard1 the instability due to the broker has been resolved. Are there any other issues?

**Comment by dwoodard1** [comment]
I don't think so. The build is failing now because of an issue with the Eclipse network. When the Sonotype service comes back up, I will examine a build to see if everything is passing.

**Comment by MMaiero** [comment]
@dwoodard1 @cdealti Sonar is broken again and I cannot perform RC builds. Could you please keep in touch with Eclipse Webmaster to solve it? Thanks.

**Comment by MMaiero** [comment]
Can we close this now, since Eclipse webmaster made some changes to the Sonar installation?
