### ISSUE TITLE
build-all script needs to incorporate the user selection of specific profile

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#567]
Currently build-all script builds Kura distribution for all platforms. I believe, the script must include a choice based on whether user needs to build the distribution at all or the user needs the distribution for all platforms or for any specific platform.

**Comment by ctron** [comment]
You already can push any arguments to the build-all script. Those arguments will be passed on to all mvn calls.

So calling buil-all -Pfoo will activate profile "foo" on all builds.

**Comment by amitjoy** [comment]
That also constrains users to know all the profiles beforehand. This could be easily solved if we provide a script which actually prompts users with proper information about whether the user wants to build the distribution or not and if yes, user would be able to choose a profile from a list of available ones.

I have been confronting this problem since months and finally I had modified the build-all script which prompts me before it starts building Kura.

**Comment by ctron** [comment]
Which is bad for automated processes ;-)

Of course you could add a second script for that.

I would rather like to see more documentation around the build, than adding just another layer of complexity which has to be maintained. Just think what happens when you add another target platform. This adds another location which you have to think of.

**Comment by amitjoy** [comment]
For automated processes, you are right but for user-centric needs, I believe, we should provide an easy-to-use utility **build-selective.sh** script.

**Comment by ctron** [comment]
Yes, that would work. And I agree that there should be a way to speed up things.

But IMHO it should be done in a way which makes the build less complicated.

**Comment by amitjoy** [comment]
Yeah you are right. The script must not complicate the build process. That is the reason, it would be really helpful for developers to use such **build-selective.sh** script to build the selective distribution build.

The problems which I have been confronting since months is that I am changing something on WebUI bundle and I want a distribution build for RPi. And if I mistakenly forget to include the specific profile while running the script or through the usual maven commands, I have to wait for the all builds to complete or I have to explicitly cancel the process as soon the build process gets complete for my specific build profile.

This gets more complex for new developers as they would never know that the different profiles do exist in Kura. They would run usual build-all script and it will run all the profiles. At least I confronted this when I started to work initially.

That's why I want it to be simplified so that anyone will have the opportunity to choose whether he/she wants to build for all the distribution profiles or selective one or no distribution at all.

**Comment by ctron** [comment]
I agree, the build process has to be more simple. But not only from an end user perspective. Also from a maintainer perspective. Right now, everything is just built. A process taking more time than necessary, but adding a new target is covered by that.

Now adding some selection mechanism should not add another location where all the possible targets are listed as well. Otherwise you end up with the next duplication of targets. And maintaining that gets more and more complex.

Like with adding s new bundle. Currently it takes about 8 different locations where a new bundle has to be added. This has to be simplified. 

Right now the build for the different targets does the same thing over and over again. That could be cleaned up. the difference between the different distributions is minimal. Beside speeding things up, this would also make it easier to maintain.

**Comment by amitjoy** [comment]
I understand your concern but until we create a target, we should provide an intermediate way to do such things. My perspective on this is to make it simple for everyone and we don't have simplicity now. Before we create a target which simplifies the situation, we can provide an interim way. What is your opinion on that?

**Comment by ctron** [comment]
Well I am totally fine with having a documented interim solution. But most interim solutions run for decades :wink:

But I agree, if it is a quick fix, do it. All I say is, that there a always two sides which need to be simplified.

**Comment by ctron** [comment]
I did made a test with "dialog" and it turned out to work rather well. There is now the `build-menu.sh` script which will detect all Maven profiles in the "distrib" project and show a menu selection. The user can activate all profiles he wants and the build is then triggered with the selected profile configuration and additional profiles provided on the command line.

@amitjoy May you can give it a try

**Comment by amitjoy** [comment]
@ctron It would be nice if you can incorporate install commands for `Dialog` based on the current running platform.

**Comment by ctron** [comment]
I am not sure I understand.

**Comment by ctron** [comment]
Oh .. you mean `yum install dialog` .. in case it is missing?

**Comment by ctron** [comment]
Ok .. I did just add a plain list without OS detection, for RHEL, Fedora and Ubuntu

**Comment by amitjoy** [comment]
Looking forward to the integration of commands for other platforms as well :thumbsup:

**Comment by ctron** [comment]
if you have some let me know ... contributions welcome :wink:

**Comment by ctron** [comment]
Ok .. I even found a command for Mac OS

**Comment by amitjoy** [comment]
That's really a nice script. I have added sugar to it. Now, it would be able to determine the running platform and execute the relevant commands to install `Dialog` if not present.

**Comment by ctron** [comment]
I added commit 6e9225d5ed589e13b632417e30db589b91f5c427 which takes over the OS detection and prints out appropriate help. See PR #576 for more information.

I think we can close this now?!
