### ISSUE TITLE
[Camel] Camel related exceptions on Kura startup

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#589]
Recently I've found that Eclipse Kura log is full of Camel-related exceptions at framework boot. 
@ctron could you please take a look?

http://pastebin.com/g3wYUrW7
 
Thanks

**Comment by ctron** [comment]
Started from inside the IDE?

**Comment by MMaiero** [comment]
No, from a raspberry pi 2

**Comment by ctron** [comment]
Looks like a start order issue. I will increment the BSL. In the end the services run fine. But I agree, it doesn't look good in the log.

**Comment by ctron** [comment]
The Camel component for "kura-cloud" is only registered after a CloudService instance is registered. It seems that  `org.eclipse.kura.core.cloud` does not register the CloudService instance during the startup although it does have a BSL of 4.

Maybe it is good idea to ditch the "default" `CloudService` handling in any case since you never are sure which service you get.

**Comment by ctron** [comment]
Should be closed by PR #606
