### ISSUE TITLE
Fix `Password` class to properly handle `null`

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#655]
IMHO the Password class should be refactored as follows:

``` java
public class Password {

    private char[] m_password;

    private Password(String password) {
        super();
        if (password != null) {
            this.m_password = password.toCharArray();
        }
    }

    private Password(char[] password) {
        super();
        this.m_password = password;
    }

    public char[] getPassword() {
        return this.m_password;
    }

    @Override
    public String toString() {
        return new String(this.m_password);
    }

    public static Password valueOf (String password)  {
       if ( password == null ) return null;
       return new Password ( password );
    }

    public static Password valueOf (char [] password)  {
       if ( password == null ) return null;
       return new Password ( password );
    }
}
```

This would allow for easy null handling. Right now lots of places in Kura just pass "null" to the constructor, which may result in a NPE later on calling toString();

**Comment by cdealti** [comment]
@ctron don't you think we should not instantiate an null Password instead?

**Comment by ctron** [comment]
> don't you think we should not instantiate an null Password instead?

What do you mean by that? If the password is `null` it will not create a new instance of `Password` but return `null` instead.

**Comment by cdealti** [comment]
I mean changing Kura checking is password is not null before creating a Password:
``
if (password != NULL) {
   p = new Password(password);
}
``
But if you think otherwise, please go ahead submitting your changes above. It looks you only added new methods and the change looks backward compatible for the API consumers and I believe there are classes extending Password (`@ProviderType`).
