### ISSUE TITLE
CQ for JointJS Updated Library

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#681]
We need to file a CQ for JointJS 0.9.9.

https://www.versioneye.com/javascript/clientio:jointjs/0.9.9

**Comment by amitjoy** [comment]
@cdealti @dwoodard1 @ctron Would you kindly have a look at this?

**Comment by amitjoy** [comment]
Actually we need to file CQ for the following files of the JointJS distribution.

- joint.min.js
- joint.min.css
- joint.shapes.devs.js

These files are inside the aforementioned distribution of JointJS.

**Comment by dwoodard1** [comment]
We have already filed a [CQ for JointJS](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12200) that was approved. Is this not sufficient?

**Comment by ctron** [comment]
Also I think we need to submit non-minified versions.

**Comment by amitjoy** [comment]
I think we need to refile a CQ for the specified version. I talked to Benjamin today about the probable time of getting it approved if we file it soon. He confirmed that as we have already filed a CQ for old version, it would not take time.


Amit Kumar Mondal
Phone: +49 176 8081 5427(tel:+49%20176%208081%205427) Email: admin@amitinside.com(mailto:admin@amitinside.com)  
Skype: arsenalnerk GitHub: a(http://blog.amitinside.com/)mitjoy
Blog: blog.amitinside.com(http://www.amitinside.com/)

**Comment by ctron** [comment]
Yes you need to file a CQ for each specific version and diff reviews are normally pretty quick.

**Comment by amitjoy** [comment]
It's actually in the archive as found in the aforementioned download link


Amit Kumar Mondal
Phone: +49 176 8081 5427(tel:+49%20176%208081%205427) Email: admin@amitinside.com(mailto:admin@amitinside.com)  
Skype: arsenalnerk GitHub: a(http://blog.amitinside.com/)mitjoy
Blog: blog.amitinside.com(http://www.amitinside.com/)

**Comment by dwoodard1** [comment]
The filed CQ was approved for 0.9.9. I posted the wrong URL earlier, [here is the correct CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10983). You have to read through the entire CQ. We originally requested 0.9.6, but due to some problematic dependencies, we requested a change from the code author. They made the requested changes, and we requested to use a newer version (0.9.9). The last line from the IP team:

"Thanks Dave.  Version 0.9.9 is approved!

Cheers,
Sharon"

**Comment by ctron** [comment]
That look all good already!
