### ISSUE TITLE
iwScantool.java sets invalid values on WifiAccessPoints strength property

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#78]
This bug was originally filed as: https://bugs.eclipse.org/bugs/show_bug.cgi?id=474906.

Original message:

The WifiAccessPoint interface says for getStrenght() method: "The current signal quality of the access point, in percent."

http://download.eclipse.org/kura/releases/1.2.0/docs/apidocs/org/eclipse/kura/net/wifi/WifiAccessPoint.html#getStrength()

This does not match when using iwScanTool to look for WifiAccessPoint, since the implementation of "iwScantool.java" around line 362
else if(line.contains("signal:")) {
	try {
		//signal: -56.00 dBm
		StringTokenizer st = new StringTokenizer(line, " ");
		st.nextToken(); //eat signal:
		final String strengthRaw = st.nextToken();
		if (strengthRaw.contains("/")) {
			// Could also be of format 39/100
			final String[] parts = strengthRaw.split("/");
			strength = (int) Float.parseFloat(parts[0]);
		} else {
			strength = Math.abs((int)Float.parseFloat(strengthRaw));
		}
	} catch (RuntimeException e) {
		s_logger.debug("Cannot parse signal strength " + line);
	}
} 

sets a better strenght to worse signal.
-56 dBm (good) --> 56 percent (bad)
-80 dBm  (bad) --> 80 percent (good)
This could potentially go over 100.

**Comment by cdealti** [comment]
@ibinshtok can you take a look?

**Comment by ibinshtok** [comment]
This should be already fixed in commit 03661a211189098ba7c5ea5a25405abd87f3b2b7
(Added signal strength conversion lookup for cases when scan reports signal strength as percentage).
the only thing that needs to be done is to modify javadocs for the getStrength() method of the WifiAccessPoint interface to reflect that we are returning signal strength in dBm.
