### ISSUE TITLE
[Kura 2.1.0 QA] Impossible to enter multiple DNS servers

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#903]
Test NET-ETH0-003 requires to enter the "appropriate" DNS servers. I do have 5 to enter and the help text in the Kura UI says "List of DNS server" and that new server can be added by clicking apply. However the is only one input field, also after pressing "apply".

**Comment by cdealti** [comment]
Can yo provide a screenshot before pressing "apply"?

**Comment by ctron** [comment]
![dnserr](https://cloud.githubusercontent.com/assets/202474/21050992/4ff4b2b2-be1e-11e6-93dd-e8ff0d56b022.png)

**Comment by cdealti** [comment]
@ibinshtok can you please take a look?

**Comment by ibinshtok** [comment]
@cdealti sure, I'll take a look at this

**Comment by ibinshtok** [comment]
@cdealti I have fixed validation for the 'DNS Servers' field to allow to enter multiple DNS servers. I've also made changes to disable 'DNS Servers' and 'Search Domains' fields if interface is configured as LAN. I did it because in the DnsMonitorServiceImpl DNS servers are added for WAN interfaces only which I think is correct. I will create a PR.

**Comment by cdealti** [comment]
See #925.

**Comment by cdealti** [comment]
Closing via #925.
