### ISSUE TITLE
[Kura 2.1.0 QA] SSID selection not always shows all SSIDs

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#911]
When testing NET-WIFI-003 I noticed that the SSID not always shows all SSIDs. Sometimes some are missing.

**Comment by cdealti** [comment]
Yes, channels above 11 are disabled. See the kura.properties file

**Comment by ctron** [comment]
No it is a channel 9 SSID

**Comment by cdealti** [comment]
Can you try with system level tools e.g. ``iwlist wlan0 scan`` and ``iw wlan0 scan``?

**Comment by ctron** [comment]
So for both command:
a) it is way faster
b) the SSID is found

Just tried again using the Kura Web UI and the SSID is missing again.

**Comment by ctron** [comment]
I will re-try this web Raspbian to see if there is a difference

**Comment by ctron** [comment]
I am not sure if there is a real difference. It seems to be a bit quicker on Raspbian. And on Raspbian I most often get a full list. Where on Fedberry I most often get an incomplete list.

But in the end I have missing SSIDs on both Raspbian and Fedberry.

**Comment by cdealti** [comment]
@pierantoniomerlino is taking a look

**Comment by ibinshtok** [comment]
I think that it is wireless tool that doesn't always returns all SSIDs. If so, there is nothing we can really do in Kura except may be scanning more than once but this takes time.

**Comment by pierantoniomerlino** [comment]
@ibinshtok I agree on your comment. However, Kura uses a hashmap to store the discovered access points, whose key is the SSID. In our office, we have several wireless nets and some of them transmit on multiple channels. So, only the last discovered SSID is added to the map. In our case, some network use channel 1 and 13 and the latter is not allowed by Kura. The result is that in some scanning the SSID is shown in the webUI, because the last discovered SSID is on channel 1, but in others is not, since the last discovered SSID is 13.
If the `kura.wifi.top.channel` in kura.properties is set to 13, all SSID are shown.
@ctron Setting  `kura.wifi.top.channel` to 13 improves the performance?

**Comment by ctron** [comment]
The channel value was previous at 11, I changed it to 13.

That didn't make the scanning faster, but it made it more complete. Indeed I do sometimes get results now which include channel 13. Which probably where missing before.

So maybe that setting should be set to 13 by default?

**Comment by pierantoniomerlino** [comment]
Thank you @ctron for the test. Indeed my question was misleading... Setting the property to 13 should make the result more complete, since it allows to scan in a wider range of channels, but it don't make the scan faster. 

Unfortunately, channels greater than 11 are not allowed in many countries due to national rules.

**Comment by ctron** [comment]
Well .. Not sure what the situation in Germany is :smile:

**Comment by cdealti** [comment]
The channel limit property issue is already described in another issue with recommendations to document this property.
As reported by Pierantonio we might also need some changes due the same SSID being broadcasted on several channels.

What about postponing this?

**Comment by pierantoniomerlino** [comment]
👍

**Comment by ctron** [comment]
So what I don't understand here is, that when I do a `iw dev wlan0 scan`, I do get all SSIDs. No matter what. Why not just use this output instead? It would provide all the information, very quickly. No missing SSIDs.

**Comment by cdealti** [comment]
Can we postpone?

**Comment by ctron** [comment]
Well if you want to leave out a bunch of valid WLAN configurations for Kura then yes.

But I wouldn't recommend that.

What is wrong with using the command suggested above?

**Comment by cdealti** [comment]
It looks to me that we are using the scan results returned by the ``wpa_supplicant`` background scan feature.
Not sure why.  @ibinshtok any thoughts?

Changing this at this stage is not feasible IMHO.

**Comment by pierantoniomerlino** [comment]
AFAIK, we are using `iw dev wlan0 scan` command also in Kura.

**Comment by cdealti** [comment]
Let's postpone this
