### ISSUE TITLE
[Kura 2.1.0 QA] DEN-CONF-005: Internal message when a "too big" number is entered

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#915]
Entering 4294967297 shows a correct error message.

Entering 429496729733333333333 as a number shows the message: `For input string: "-429496729733333333333"`

**Comment by ctron** [comment]
Also fails DEN-CONF-016

**Comment by cdealti** [comment]
nice catch

**Comment by markoer** [comment]
Partly a duplicate of #889.

**Comment by markoer** [comment]
This happens when the value is outside of java's allowed interval for the type. And when `org.eclipse.kura.web.client.ui.AbstractServicesUi`'s `validateTextBox` parses the number, NumberFormatException is thrown and the message in question is exactly its message.

Possible options for a fix:
* use BigInteger and its shortValueExact, intValueExact, longValueExact, byteValueExact
* validate and evaluate string manually
