### ISSUE TITLE
org.eclipse.kura.asset.provider provides API and service implementation

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#932]
The bundle `org.eclipse.kura.asset.provider` provides base classes and a service implementation at the same time. That way it is impossible to exchange the service implementation with a different implementation.

As we are using OSGi we should follow the idea of splitting up API/base classes and internal service implementation.

Currently the "web" bundle requires a reference to `org.eclipse.kura.asset.provider` in order to use `BaseChannelDescriptor` and thus Kura an only be used with the single implementation of `org.eclipse.kura.asset.provider`.

**Comment by amitjoy** [comment]
This is a design decision that we have to consider thinking of its pros and cons in OSGi dynamic environment. You are absolutely right. It is not possible to change the implementation at runtime. It has a history behind it.

`Asset` is a concept that is introduced with `Wires`. `Asset` is a logical representation of device in `Kura` (not restricted to `Wires`). To perform read/write operations on a physical device, users can use `Asset-Driver component model `in `Kura`. We provide the base implementation of `Asset` in `BaseAsset`.

`Asset` is also used as a logical node or `Wire Component` in `Kura Wires` dataflow graph. As `BaseAsset` provides all the necessary implementations to associate `Driver` for reading and writing data from physical devices, `WireAsset` (An implementation of `Asset` and `WireComponent`) leverages the basic implementation of `Asset` (`BaseAsset`).

Now, why did we extend `BaseAsset`?

To leverage the implemented functionalities of `Asset`. So, when an user uses `Wires` with a `WireAsset` configured the the dataflow graph (`Wire Graph`), only one service component is registered - `WireAsset`. And when an user uses `Asset-Driver component model` without `Wires`, only `Asset` service component is registered. 

Why `BaseAsset` is not associated with `WireAsset`?

The lifecycles of `BaseAsset` and `WireAsset` are managed by OSGi configuration service and hence, we didn't choose to create `BaseAsset` manually and inject to `WireAsset`. This could have prevented us to manage the lifecycle of `BaseAsset` in runtime. That's why `WireAsset` does not associate `BaseAsset` but extends.

**Comment by ctron** [comment]
Since this is new in Kura 3.0 I would say we can ignore "backward compatibility".

So technically, what speaks against separating those two into different bundles?

**Comment by amitjoy** [comment]
The two bundles are kept separated, depending on the implementations it provides. `org.eclipse.kura.asset.provider` provides `BaseAsset` implementation whereas `org.eclipse.kura.wire.component.provider` provides all the implementations of `Wire Components` including `WireAsset`.

**Comment by ctron** [comment]
I meant the bundle "org.eclipse.kura.asset.provider".

**Comment by amitjoy** [comment]
If I have understood the question correctly, `org.eclipse.kura.asset.provider` provides the implementation for `Asset-Driver Component Model` that can be used in isolation (without `Wires`). And that's why it is kept separated.

**Comment by ctron** [comment]
I do want to split up the bundle "org.eclipse.kura.asset.provider". Not merge it with something else.

**Comment by amitjoy** [comment]
As I have mentioned earlier, we need OSGi to manage the lifecycles of `BaseAsset` service component and `WireAsset` service component. If we split up `org.eclipse.kura.asset.provider` bundle to have a fragment to contain `WireAsset`, it is not possible to export it as fragment does not allow to export services.

**Comment by ctron** [comment]
Sure, but the instance can be exported from any bundle. Not necessarily just this one. And not necessarily from a fragment.

**Comment by amitjoy** [comment]
So you mean, the instance of the service component can be exported from any bundle. But what would be the advantage of exporting the instance from other bundle?

**Comment by ctron** [comment]
You are not exporting BaseAsset instances from this bundle. I will dig into this next year and try make an example for you.

**Comment by amitjoy** [comment]
Actually `BaseAsset` instances are exported from `org.eclipse.kura.asset.provider` bundle when it is required. That is, when user only uses `Asset-Driver component model` to perform read/write operations, `BaseAsset` instances are exported from `org.eclipse.kura.asset.provider`  bundle. But while using Kura Wires, no `BaseAsset` instance is created rather `WireAsset` instances are exported from `org.eclipse.kura.wire.component.provider` bundle.

**Comment by ctron** [comment]
@amitjoy Please have a look at and let me know if you see any issues with that.

**Comment by amitjoy** [comment]
Previously I thought you were talking about the extensibility behaviour of `BaseAsset` as it is extended by `WireAsset` in another bundle. I am completely fine with separating the utility services in different bundles. 👍

**Comment by ctron** [comment]
Cool. So this can be merged from your perspective?

**Comment by amitjoy** [comment]
I don't see any problem with that 👍. You can merge this.
